/* Veyra — local-first fitness & nutrition coach. No backend required. */
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DAY=86400000;
const now=()=>new Date();
const iso=d=>new Date(d).toISOString().slice(0,10);
const localDateKey=d=>{const x=new Date(d),y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),day=String(x.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const today=()=>localDateKey(now());
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-4);
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const fmt=n=>Math.round(Number(n)||0).toLocaleString();
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));

const DEFAULT={
  schemaVersion:4,
  onboardingComplete:false,onboardingSkipped:false,
  profile:{name:'',diet:'',goal:'',goalText:'',calorieGoal:null,proteinGoal:null,carbGoal:null,fatGoal:null,fiberGoal:null,waterGoal:null,units:'imperial',distanceUnits:'mi',pantryPreference:'pantry-only',foodsAvoid:'',dietaryRestrictions:[],favoriteCuisines:[],equipment:'',ageGroup:'',age:null,height:null,weight:null,sex:'',activityLevel:'',trainingDays:null,sessionMinutes:null,trainingPreference:'',experienceLevel:'',sleepGoal:null,createdProfileAt:null},
  theme:'system',demo:false,createdAt:Date.now(),lastActive:'',streak:0,
  meals:[],activities:[],sleep:[],water:{},pantry:[],pantryRecents:[],savedMeals:[],
  routines:[{id:'push',name:'Push Day',days:['Mon','Thu'],exercises:[
    {name:'Bench Press',kind:'reps',muscle:'Chest',icon:'🏋️',sets:3,target:'8–10'},
    {name:'Incline Dumbbell Press',kind:'reps',muscle:'Chest',icon:'↗️',sets:3,target:'8–12'},
    {name:'Shoulder Press',kind:'reps',muscle:'Shoulders',icon:'🙌',sets:3,target:'8–12'},
    {name:'Lateral Raise',kind:'reps',muscle:'Shoulders',icon:'🪽',sets:3,target:'12–15'},
    {name:'Tricep Pushdown',kind:'reps',muscle:'Triceps',icon:'💪',sets:3,target:'10–15'},
    {name:'Plank',kind:'time',muscle:'Core',icon:'⏱️',sets:3,target:'45 sec'}
  ]},{id:'pull',name:'Pull Day',days:['Tue','Fri'],exercises:[
    {name:'Lat Pulldown',kind:'reps',muscle:'Back',icon:'⬇️',sets:3,target:'8–12'},
    {name:'Seated Cable Row',kind:'reps',muscle:'Back',icon:'🚣',sets:3,target:'8–12'},
    {name:'Face Pull',kind:'reps',muscle:'Rear delts',icon:'🎯',sets:3,target:'12–15'},
    {name:'Bicep Curl',kind:'reps',muscle:'Biceps',icon:'💪',sets:3,target:'10–12'}
  ]},{id:'legs',name:'Leg Day',days:['Wed','Sat'],exercises:[
    {name:'Squat',kind:'reps',muscle:'Quads',icon:'🦵',sets:3,target:'6–10'},
    {name:'Romanian Deadlift',kind:'reps',muscle:'Hamstrings',icon:'🏋️',sets:3,target:'8–10'},
    {name:'Leg Press',kind:'reps',muscle:'Quads',icon:'🦿',sets:3,target:'10–15'},
    {name:'Calf Raise',kind:'reps',muscle:'Calves',icon:'⬆️',sets:3,target:'12–20'},
    {name:'Wall Sit',kind:'time',muscle:'Quads',icon:'⏱️',sets:2,target:'45 sec'}
  ]}],
  workouts:[], notes:[], favorites:[], experiments:[], history:[],
  spotify:{clientId:'',connected:false,displayName:'',accessToken:'',refreshToken:'',tokenExpiresAt:0,nowPlaying:null},
  settings:{reminders:false,reducedMotion:false,advancedNutrition:false,showAds:false}
};

let state=load(); let route=(location.hash||'#today').slice(1); let deferredInstall=null; let restTimer=null; let restRemaining=0; let liveWorkout=null;
function load(){try{const raw=JSON.parse(localStorage.getItem('veyra-state'));if(!raw)return structuredClone(DEFAULT);const noRealProfile=!raw.profile?.name&&!raw.profile?.createdProfileAt;const looksLikeOldDemo=raw.demo===true||!raw.schemaVersion||(raw.schemaVersion<4&&noRealProfile);if(looksLikeOldDemo){const fresh=structuredClone(DEFAULT);fresh.theme=raw.theme||fresh.theme;fresh.settings=deepMerge(fresh.settings,raw.settings||{});fresh.spotify=deepMerge(fresh.spotify,raw.spotify||{});return fresh}const merged=deepMerge(structuredClone(DEFAULT),raw);merged.schemaVersion=4;return merged;}catch{return structuredClone(DEFAULT)}}
function deepMerge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k]&&typeof a[k]==='object'&&!Array.isArray(a[k])) a[k]=deepMerge(a[k],b[k]); else a[k]=b[k]}return a}
function save(){localStorage.setItem('veyra-state',JSON.stringify(state));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function totals(date=today()){return state.meals.filter(x=>x.date===date).reduce((a,x)=>({cal:a.cal+x.cal,p:a.p+x.p,c:a.c+x.c,f:a.f+x.f,fiber:a.fiber+(x.fiber||0),sugar:a.sugar+(x.sugar||0)}),{cal:0,p:0,c:0,f:0,fiber:0,sugar:0})}
function active(date=today()){return state.activities.filter(x=>x.date===date).reduce((a,x)=>a+(x.calories||0),0)}
function pct(v,g){return g>0?clamp(Math.round(v/g*100),0,100):0}
function metric(icon,label,value,goal,unit){if(!(goal>0))return `<button class="card metric metric-unset" data-action="editGoals"><div class="metric-top"><div><small>${label}</small><div class="big">${fmt(value)}<small>${unit}</small></div></div><div class="metric-icon">${icon}</div></div><small>Set your ${label.toLowerCase()} goal →</small><div class="progress-track"><div class="progress-fill" style="width:0%"></div></div></button>`;return `<div class="card metric"><div class="metric-top"><div><div class="metric-label-row"><small>${label}</small><button class="tiny-edit" data-action="editGoals">Edit</button></div><div class="big">${fmt(value)}<small>${unit}</small></div></div><div class="metric-icon">${icon}</div></div><small>${fmt(goal-value)>0?fmt(goal-value)+' '+unit+' left of '+fmt(goal)+unit:'Goal reached • '+fmt(goal)+unit}</small><div class="progress-track"><div class="progress-fill" style="width:${pct(value,goal)}%"></div></div></div>`}
function plainMetric(icon,label,value,sub=''){return `<div class="card metric"><div class="metric-top"><div><small>${label}</small><div class="big plain-big">${value}</div></div><div class="metric-icon">${icon}</div></div>${sub?`<small>${sub}</small>`:''}</div>`}

const NAV=[['today','⌂','Today'],['food','🍴','Nutrition'],['train','🏋','Train'],['progress','↗','Progress'],['coach','✦','Coach'],['profile','👤','Profile'],['recipes','👨‍🍳','Recipes'],['pantry','▣','Pantry'],['lab','🧪','Veyra Lab'],['sleep','☾','Sleep'],['data','◫','Public Data'],['creator','◎','About Creator'],['about','◉','Methodology'],['settings','⚙','Settings']];
function renderNav(){const item=([id,ic,l])=>`<button class="nav-btn ${route===id?'active':''}" data-route="${id}"><span class="nav-icon">${ic}</span><span>${l}</span></button>`;$('#desktopNav').innerHTML=NAV.map(item).join('');$('#mobileNav').innerHTML=NAV.slice(0,5).map(item).join('');$$('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));}
function go(r){route=r;location.hash=r;render();window.scrollTo({top:0,behavior:'smooth'})}
function render(){renderNav(); const fn=views[route]||views.today;$('#view').innerHTML=fn(); bind();const pi=$('#profileInitial');if(pi)pi.textContent=(state.profile.name||'?').trim().charAt(0).toUpperCase()||'?'; $('#view').focus({preventScroll:true});}

function hero(kicker,title,desc,actions=''){return `<div class="hero"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div>${actions?`<div class="hero-actions">${actions}</div>`:''}</div>`}
function quick(icon,title,sub,action){return `<button class="quick-card" data-action="${action}"><span class="quick-icon">${icon}</span><b>${title}</b><small>${sub}</small></button>`}
function todayView(){const t=totals(), burn=active(), sleep=state.sleep.find(x=>x.date===today())?.hours||0, water=state.water[today()]||0; const nexus=nexusActions(t,burn,sleep,water);
return hero('Veyra Nexus','Your day, connected.',`Nutrition, training, recovery and habits in one private local model. ${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}.`,`<button class="primary" data-action="quickAdd">+ Log</button><button class="secondary" data-action="startWorkout">Start workout</button>`)+`${!state.onboardingComplete?`<div class="setup-banner"><div><span class="eyebrow">Personalize Veyra</span><h2>Your dashboard starts with you — not demo numbers.</h2><p>Tell Veyra your goal and targets, or skip them for now. You can change everything anytime.</p></div><button class="primary" data-action="editGoals">Finish setup</button></div>`:''}
<div class="quick-actions">${quick('📸','Veyra Lens','Scan food, labels or activity','lens')}${quick('🎙️','Talk to Veyra','Hands-free logging','voice')}${quick('✨','Fill My Day','Context-aware ideas','fillDay')}${quick('📲','Import Activity','Screenshot → log','activityImport')}${quick('🥗','Pantry Camera','Ingredients → recipes','pantryCamera')}${quick('▶','Replay','Search your history','replay')}</div>
<div class="grid grid-4">${metric('🔥','Calories',t.cal,state.profile.calorieGoal,' kcal')}${metric('💪','Protein',t.p,state.profile.proteinGoal,'g')}${metric('💧','Water',water,state.profile.waterGoal,' oz')}${plainMetric('☾','Sleep',sleep?sleep+' h':'Not logged','')}</div>
<div class="dashboard-grid"><div class="card chart-card"><div class="card-head"><div><h2>Live Progress</h2><small>Tap a range. Predictive view shows a range, not a promise.</small></div><div class="chart-toolbar" id="chartTabs">${['Today','Week','Month','YTD','All Time','Predictive'].map((x,i)=>`<button class="seg ${i===0?'active':''}" data-chart="${x}">${x}</button>`).join('')}</div></div><div id="mainChart" class="chart-wrap">${chartSVG('Today')}</div></div>
<div class="card"><div class="card-head"><h2>✦ Veyra Nexus</h2><small>Next best actions</small></div><div class="insight-list">${nexus.map((x,i)=>`<button class="insight" data-action="${x.action}"><span class="insight-num">${i+1}</span><div><b>${x.title}</b><small>${x.body}</small></div><span>›</span></button>`).join('')}</div><div class="callout">Nexus connects food, workouts, sleep, pantry, preferences and history. Suggestions adapt as your day changes.</div></div></div>
<div class="grid grid-2" style="margin-top:16px"><div class="card"><div class="card-head"><h2>Today’s timeline</h2><button class="ghost" data-route="food">Edit</button></div>${timeline()}</div><div class="card spotify-card"><div class="card-head"><h2><span class="spotify-dot">●</span> Workout Music</h2><small>Spotify</small></div>${spotifyPanel()}</div></div>
<div class="ad-slot" ${state.settings.showAds?'':'style="display:none"'}></div>
<div class="card" style="margin-top:16px"><div class="card-head"><div><h2>Public data, put in context</h2><small>Credible benchmarks — never used to judge your body.</small></div><button class="ghost" data-route="data">Explore data</button></div><div class="stat-strip"><div class="public-stat"><b>31%</b><small>of adults worldwide were insufficiently active in 2022.</small><a class="source-link" href="https://www.who.int/news-room/fact-sheets/detail/physical-activity" target="_blank" rel="noopener">WHO source ↗</a></div><div class="public-stat"><b>150 min</b><small>moderate-intensity activity per week is the CDC adult benchmark.</small><a class="source-link" href="https://www.cdc.gov/physical-activity-basics/guidelines/adults.html" target="_blank" rel="noopener">CDC source ↗</a></div><div class="public-stat"><b>2 days</b><small>of muscle-strengthening activity per week is the CDC adult benchmark.</small><a class="source-link" href="https://www.cdc.gov/physical-activity-basics/guidelines/adults.html" target="_blank" rel="noopener">CDC source ↗</a></div></div></div>`}

function nexusActions(t,burn,sleep,water){const a=[],waterUnit=state.profile.units==='metric'?'mL':'oz';if(!state.onboardingComplete)a.push({title:'Set your targets',body:'Personalize calories, macros, hydration and your main goal whenever you are ready.',action:'editGoals'});if(state.profile.proteinGoal>0&&t.p<state.profile.proteinGoal*.72)a.push({title:'Close the protein gap',body:`About ${Math.max(0,state.profile.proteinGoal-t.p)}g remains based on the target you chose.`,action:'fillDay'});if(state.profile.waterGoal>0&&water<state.profile.waterGoal*.6)a.push({title:'Hydration check-in',body:`You’ve logged ${water} ${waterUnit} today.`,action:'water'});if(sleep&&sleep<7)a.push({title:'Keep training flexible',body:'This sleep log is under 7 hours; consider keeping today’s training flexible.',action:'sleep'});if(!state.activities.some(x=>x.date===today()))a.push({title:'Move when it fits',body:'No activity logged yet. Start a routine or import a screenshot.',action:'startWorkout'});if(a.length<3&&state.streak>0)a.push({title:'Review your trend',body:`You’ve logged ${state.streak} day${state.streak===1?'':'s'} of engagement.`,action:'progress'});if(a.length<3)a.push({title:'Plan with your pantry',body:state.pantry.length?`${state.pantry.length} ingredients are ready for dynamic meal ideas.`:'Add a few ingredients and Veyra can turn them into meal ideas.',action:'recipes'});return a.slice(0,3)}
function timeline(){
  const mealEvents=state.meals.filter(x=>x.date===today()).map(x=>({...x,kind:'meal',icon:'🍽️',label:x.name,sub:`${x.meal} • ${x.cal} kcal • ${x.p}g protein`,target:`data-edit="meal:${x.id}"`}));
  const activityEvents=state.activities.filter(x=>x.date===today()).map(x=>({...x,kind:'activity',icon:'🏃',label:x.type,sub:[x.environment||'',x.duration?`${x.duration} min`:'',x.distance?`${x.distance} ${state.profile.distanceUnits||(state.profile.units==='metric'?'km':'mi')}`:'',x.calories?`~${x.calories} kcal reported/estimated`:'calories not entered'].filter(Boolean).join(' • '),target:`data-edit="activity:${x.id}"`}));
  const workoutEvents=(state.workouts||[]).filter(x=>x.date===today()).map(x=>({...x,kind:'workout',icon:'🏋️',label:x.routine||'Workout',time:x.time||x.startTime||x.endTime||'18:00',sub:[x.duration?`${x.duration} min`:'',`${(x.exercises||[]).length} exercise${(x.exercises||[]).length===1?'':'s'}`].filter(Boolean).join(' • '),target:'data-route="train"'}));
  const recoveryEvents=(state.sleep||[]).filter(x=>x.date===today()).map(x=>({...x,kind:'recovery',icon:'☾',label:'Sleep & recovery',time:x.time||'07:00',sub:[x.hours?`${x.hours} h sleep`:'',x.energy?`energy ${x.energy}/5`:'',x.soreness?`soreness ${x.soreness}/5`:''].filter(Boolean).join(' • '),target:'data-route="sleep"'}));
  const events=[...mealEvents,...activityEvents,...workoutEvents,...recoveryEvents].sort((a,b)=>(a.time||'').localeCompare(b.time||''));
  return events.length?`<div class="timeline">${events.map(e=>`<button class="timeline-item" ${e.target}><time>${e.time||'—'}</time><span class="timeline-icon">${e.icon}</span><span><b>${esc(e.label)}</b><small>${esc(e.sub)}</small></span><span>›</span></button>`).join('')}</div>`:`<div class="empty">Nothing logged yet. Tap + to start.</div>`
}
function chartSVG(mode='Today'){let pts=[]; let label='Calories'; if(mode==='Today'){const xs=[6,9,12,15,18,21];const t=totals();const cumulative=[0,Math.round(t.cal*.22),Math.round(t.cal*.58),Math.round(t.cal*.7),Math.round(t.cal*.92),t.cal];pts=xs.map((x,i)=>({x:i,y:cumulative[i]}));}
else {const n=mode==='Week'?7:mode==='Month'?30:mode==='YTD'?Math.min(180,state.history.length):state.history.length;pts=state.history.slice(-n).map((h,i)=>({x:i,y:h.cal}));}
if(mode==='Predictive'){label='Projected trend';const hist=state.history.slice(-30);const base=hist.at(-1)?.weight;if(base)pts=Array.from({length:12},(_,i)=>({x:i,y:base-i*.12}));else pts=[];}
if(!pts.length)return `<div class="chart-empty"><span>📈</span><b>No progress data yet</b><small>Start logging food, workouts, sleep or activity and this graph will build from your real data.</small></div>`;const w=700,h=240,p=30;const ys=pts.map(p=>p.y);const min=Math.min(...ys,0),max=Math.max(...ys,1);const X=i=>p+(i/Math.max(1,pts.length-1))*(w-p*2);const Y=v=>h-p-((v-min)/(max-min||1))*(h-p*2);const path=pts.map((q,i)=>`${i?'L':'M'}${X(i).toFixed(1)},${Y(q.y).toFixed(1)}`).join(' ');const area=path+` L${X(pts.length-1)},${h-p} L${X(0)},${h-p} Z`;
let band='';if(mode==='Predictive'){const top=pts.map((q,i)=>`${i?'L':'M'}${X(i)},${Y(q.y+1.8)}`).join(' '),bot=[...pts].reverse().map((q,j)=>`L${X(pts.length-1-j)},${Y(q.y-1.8)}`).join(' ');band=`<path d="${top} ${bot} Z" fill="rgba(139,92,246,.12)"/>`}
return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${label} chart">${[.25,.5,.75,1].map(v=>`<line class="chart-gridline" x1="${p}" x2="${w-p}" y1="${p+(h-p*2)*(1-v)}" y2="${p+(h-p*2)*(1-v)}"/>`).join('')}<defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2be8d0" stop-opacity=".28"/><stop offset="1" stop-color="#2be8d0" stop-opacity="0"/></linearGradient></defs>${band}<path d="${area}" fill="url(#g)"/><path class="chart-line-a" d="${path}" stroke="#2be8d0" stroke-width="3"/>${pts.filter((_,i)=>pts.length<15||i%Math.ceil(pts.length/10)===0).map((q,i)=>`<circle cx="${X(pts.indexOf(q))}" cy="${Y(q.y)}" r="3.5" fill="#2be8d0"><title>${Number(q.y).toFixed(mode==='Predictive'?1:0)}</title></circle>`).join('')}<text class="chart-label" x="${p}" y="16">${label}</text></svg>`}

function foodView(){const t=totals();return hero('Nutrition','Food logging without friction.','Search, speak, scan, save, correct and edit anything — with uncertainty shown instead of hidden.',`<button class="primary" data-action="addFood">+ Add food</button><button class="secondary" data-action="lens">📸 Scan</button>`)+`
<div class="grid grid-4">${metric('🔥','Calories',t.cal,state.profile.calorieGoal,' kcal')}${metric('💪','Protein',t.p,state.profile.proteinGoal,'g')}${metric('🌾','Fiber',t.fiber,state.profile.fiberGoal,'g')}${plainMetric('🍬','Sugar',fmt(t.sugar)+'g','Logged today')}</div>
<div class="card" style="margin-top:16px"><div class="card-head"><div><h2>Meals</h2><small>Tap any item to edit. Confidence explains how certain Veyra is.</small></div><button class="ghost" data-action="copyYesterday">Copy yesterday</button></div>${mealList()}</div>
<div class="grid grid-2" style="margin-top:16px"><div class="card"><div class="card-head"><h2>Saved meals</h2><button class="ghost" data-action="saveCurrentMeal">Save current</button></div>${state.savedMeals.map(x=>`<button class="food-row" data-saved="${esc(x.name)}"><span class="food-emoji">⭐</span><span><b>${esc(x.name)}</b><small>${x.cal} kcal • ${x.p}g protein</small></span><span>+ Log</span></button>`).join('')}<div class="profile-links"><button class="secondary" data-action="restaurant">Restaurant intelligence</button><button class="secondary" data-action="flexDay">Flexible Day</button><button class="secondary" data-action="recipeCalc">Recipe calculator</button></div></div><div class="card"><div class="card-head"><h2>Advanced nutrients</h2><label class="switch-label"><input id="advancedToggle" type="checkbox" ${state.settings.advancedNutrition?'checked':''}> Optional</label></div><p class="muted">Main view stays focused on calories, protein, carbs, fats, fiber and sugar. Advanced micronutrients are available when you want them.</p>${state.settings.advancedNutrition?`<div class="empty compact">Micronutrient totals appear when foods include verified micronutrient data. Veyra does not invent percentages for missing data.</div>`:''}</div></div>`}
function mealList(){const groups=['Breakfast','Lunch','Dinner','Snack'];return groups.map(g=>{const arr=state.meals.filter(x=>x.date===today()&&x.meal===g);return `<div class="meal-group"><div class="meal-title"><b>${g}</b><button class="text-btn" data-mealadd="${g}">+ Add</button></div>${arr.length?arr.map(x=>`<button class="food-row" data-edit="meal:${x.id}"><span class="food-emoji">${g==='Breakfast'?'🥣':g==='Lunch'?'🥗':g==='Dinner'?'🍲':'🥤'}</span><span><b>${esc(x.name)}</b><small>${x.time} • ${x.cal} kcal • P ${x.p}g • C ${x.c}g • F ${x.f}g</small></span><span><span class="confidence">${x.confidence||85}%</span></span></button>`).join(''):`<div class="empty compact">Nothing logged.</div>`}</div>`}).join('')}

function trainView(){return hero('Veyra Live','Train without leaving the flow.','Interactive routines, reps or timed sets, rest tracking, substitutions, notes, voice control and progressive-overload history.',`<button class="primary" data-action="startWorkout">▶ Start workout</button><button class="secondary" data-action="addRoutine">+ Routine</button>`)+`
<div class="routine-grid">${state.routines.map(r=>`<div class="card routine-card"><div class="card-head"><div><h2>${esc(r.name)}</h2><small>${r.exercises.length} exercises • ${r.days.join(', ')}</small></div><button class="primary" data-routine="${r.id}">Start</button></div><div class="exercise-mini-list">${r.exercises.map(e=>`<div class="exercise-mini"><span>${e.icon}</span><div><b>${e.name}</b><small>${e.sets} × ${e.target} • ${e.muscle}</small></div></div>`).join('')}</div></div>`).join('')}</div>
<div class="grid grid-2" style="margin-top:16px"><div class="card"><div class="card-head"><h2>Muscle Map</h2><small>Training coverage, not appearance</small></div>${state.workouts.length?trainingCoverage():`<div class="empty">Complete workouts and Veyra will build this from the exercises you actually log.</div>`}</div><div class="card"><div class="card-head"><h2>Progressive overload</h2><small>Your real history</small></div>${state.workouts.length>=2?`<div class="pr-card"><span class="badge">📈</span><div><b>Trend available</b><small>Veyra compares your completed sets over time and highlights changes once enough sessions exist.</small></div></div>`:`<div class="empty">Log at least two workouts to start comparing volume, reps and load.</div>`}<div class="callout">Veyra emphasizes performance trends and consistency rather than body comparison.</div></div></div>`}

function trainingCoverage(){const counts={};for(const w of state.workouts){for(const ex of (w.exercises||[])){const m=ex.muscle||'Other';counts[m]=(counts[m]||0)+1}}const entries=Object.entries(counts);if(!entries.length)return `<div class="empty">No muscle-group data yet.</div>`;const max=Math.max(...entries.map(x=>x[1]));return `<div class="muscle-map"><div class="body-figure">◯<br>╱│╲<br>╱ ╲</div><div class="muscle-bars">${entries.slice(0,8).map(([m,n])=>{const v=Math.round(n/max*100);return `<div><span>${esc(m)}<b>${v}%</b></span><div class="progress-track"><div class="progress-fill" style="width:${v}%"></div></div></div>`}).join('')}</div></div>`}

function progressView(){return hero('Progress','See the story, not just the numbers.','Today, week, month, year-to-date, all-time and uncertainty-aware predictive views.',`<button class="secondary" data-action="weeklyReport">Weekly report</button>`)+`
<div class="card chart-card"><div class="card-head"><div><h2>Unified progress graph</h2><small>Nutrition • activity • strength • recovery</small></div><div class="chart-toolbar" id="chartTabs">${['Today','Week','Month','YTD','All Time','Predictive'].map((x,i)=>`<button class="seg ${i===1?'active':''}" data-chart="${x}">${x}</button>`).join('')}</div></div><div id="mainChart" class="chart-wrap">${chartSVG('Week')}</div></div>
<div class="grid grid-3" style="margin-top:16px"><div class="card"><div class="card-head"><h2>🔥 ${state.streak?state.streak+'-day':'Start your'} streak</h2><small>Engagement, not perfection</small></div><div class="streak-grid">${Array.from({length:28},(_,i)=>`<div class="streak-day ${i<Math.min(state.streak,28)?'hit':''}">${i+1}</div>`).join('')}</div></div><div class="card"><div class="card-head"><h2>Personal records</h2></div>${personalRecords()}</div><div class="card"><div class="card-head"><h2>Achievements</h2></div><div class="achievement-grid">${achievementRows()}</div></div></div>`}

function personalRecords(){const rows=[];if(state.workouts.length)rows.push(`${state.workouts.length} workout${state.workouts.length===1?'':'s'} completed`);const runs=state.activities.filter(x=>/run/i.test(x.type||''));if(runs.length){const longest=Math.max(...runs.map(x=>+x.distance||0));if(longest>0)rows.push(`Longest run • ${longest.toFixed(1)} ${state.profile.distanceUnits||(state.profile.units==='metric'?'km':'mi')}`)}if(state.activities.length)rows.push(`${state.activities.length} activit${state.activities.length===1?'y':'ies'} logged`);return rows.length?rows.map(x=>`<div class="pr-card"><span>🏆</span><b>${x}</b></div>`).join(''):`<div class="empty">Your records will appear after you start logging workouts and activities.</div>`}
function achievementRows(){const defs=[['🔥','Consistency',state.streak>=3],['🏋️','10 Workouts',state.workouts.length>=10],['🥗','Recipe Maker',state.savedMeals.length>=1],['📈','First Trend',state.history.length>=2]];return defs.map(([ic,n,ok])=>`<div class="achievement ${ok?'':'locked'}"><div class="badge">${ic}</div><b>${n}</b><small>${ok?'Unlocked':'Not yet'}</small></div>`).join('')}

function coachView(){return hero('Veyra Coach','Ask your own fitness history.','A local-first assistant for navigation, food, recipes, routines and patterns. It does not replace medical or professional advice.',`<button class="secondary" data-action="voice">🎙️ Talk</button>`)+`
<div class="coach-layout"><div class="card coach-card"><div id="chatLog" class="chat-log"><div class="bubble bot"><b>Veyra Coach</b><br>Ask me about today, your pantry, a workout, your history, or what you can make next.</div></div><form id="coachForm" class="coach-input"><input id="coachInput" placeholder="Try: What should I eat next?" autocomplete="off"><button class="primary">Send</button></form></div><div class="card"><div class="card-head"><h2>Try asking</h2></div>${['What did I eat today?','How has my protein been this week?','What can I make from my pantry?','Start my Push Day','What muscle groups are undertrained?','Show my progress','I ate a yogurt bowl','I ran for 30 minutes'].map(q=>`<button class="command-result coach-prompt">${q}</button>`).join('')}</div></div>`}

function recipesView(){const recs=recipeMatches();return hero('Smart Recipes','Cook from what you actually have.','Pantry-aware, restriction-aware recipes ranked by fit, speed and nutrition.',`<button class="primary" data-route="pantry">Edit pantry</button><button class="secondary" data-action="pantryCamera">📸 Scan ingredients</button>`)+`<div class="recipe-grid">${recs.map(r=>recipeCard(r)).join('')}</div><div class="card" style="margin-top:16px"><div class="card-head"><h2>Fill My Day</h2><small>Based on remaining nutrition + preferences</small></div>${fillDayRows()}</div>`}
function recipeLibrary(){return [
{name:'Loaded Veggie Protein Wrap',emoji:'🌯',cuisine:'Mexican',diet:['vegetarian'],time:10,cal:430,p:35,ingredients:['tortillas','crumbles','spinach','cheese','bell peppers'],tag:'High protein'},
{name:'Greek Yogurt Power Bowl',emoji:'🥣',cuisine:'Greek',diet:['vegetarian'],time:5,cal:360,p:29,ingredients:['Greek yogurt','fruit','oats'],tag:'Fast'},
{name:'Black Bean Rice Bowl',emoji:'🥗',cuisine:'Mexican',diet:['vegan','vegetarian'],time:15,cal:510,p:24,ingredients:['rice','black beans','spinach','peppers'],tag:'High fiber'},
{name:'Protein Pantry Skillet',emoji:'🍳',cuisine:'American',diet:['vegetarian'],time:14,cal:420,p:33,ingredients:['crumbles','black beans','spinach','peppers'],tag:'Pantry fit'},
{name:'Tandoori Tofu Bowl',emoji:'🍛',cuisine:'Indian',diet:['vegan','vegetarian'],time:22,cal:475,p:34,ingredients:['tofu','rice','spinach','yogurt','spices'],tag:'Flavor-forward'},
{name:'Paneer Power Bowl',emoji:'🫓',cuisine:'Indian',diet:['vegetarian'],time:20,cal:495,p:32,ingredients:['paneer','rice','spinach','peppers'],tag:'Protein-focused'},
{name:'Mediterranean Chickpea Bowl',emoji:'🫒',cuisine:'Mediterranean',diet:['vegan','vegetarian'],time:12,cal:445,p:23,ingredients:['chickpeas','spinach','tomato','cucumber','tahini'],tag:'Fresh'},
{name:'Tofu Teriyaki Rice Bowl',emoji:'🍱',cuisine:'Japanese',diet:['vegan','vegetarian'],time:18,cal:490,p:31,ingredients:['tofu','rice','broccoli','soy sauce'],tag:'Balanced'},
{name:'Thai Peanut Tofu Bowl',emoji:'🍜',cuisine:'Thai',diet:['vegan','vegetarian'],time:18,cal:485,p:30,ingredients:['tofu','rice','vegetables','peanut sauce'],tag:'Pantry adaptable'},
{name:'Italian Lentil Pasta',emoji:'🍝',cuisine:'Italian',diet:['vegan','vegetarian'],time:20,cal:460,p:28,ingredients:['lentil pasta','tomato sauce','spinach'],tag:'Comfort food'},
{name:'Creamy Yogurt Taco Sauce',emoji:'🥙',cuisine:'Mexican',diet:['vegetarian'],time:6,cal:120,p:10,ingredients:['Greek yogurt','spices'],tag:'Add-on'}]}
function recipeMatches(opts={}){const pantry=state.pantry.map(x=>x.toLowerCase());const fav=(state.profile.favoriteCuisines||[]).map(x=>x.toLowerCase());const diet=(opts.diet||state.profile.diet||'').toLowerCase();const avoid=[state.profile.foodsAvoid,...(state.profile.dietaryRestrictions||[])].join(' ').toLowerCase();const maxCal=opts.maxCal||Infinity;const minProtein=opts.minProtein||0;return recipeLibrary().filter(r=>r.cal<=maxCal&&r.p>=minProtein).filter(r=>!diet||diet==='omnivore'||diet==='custom'||r.diet.includes(diet)||diet==='vegetarian'&&r.diet.includes('vegan')).filter(r=>!r.ingredients.some(i=>avoid&&avoid.includes(i.toLowerCase()))).map(r=>{const pantryHits=r.ingredients.filter(i=>pantry.some(p=>p.includes(i.toLowerCase().split(' ')[0])||i.toLowerCase().includes(p.split(' ')[0]))).length;const cuisineBoost=fav.includes(r.cuisine.toLowerCase())?3:0;return {...r,_score:pantryHits*4+cuisineBoost+(r.p>=minProtein?2:0)}}).sort((a,b)=>b._score-a._score||b.p-a.p)}
function recipeCard(r){return `<button class="recipe-card" data-recipe="${esc(r.name)}"><div class="recipe-art">${r.emoji}</div><div class="recipe-body"><span class="confidence">${r.tag}</span><h3>${r.name}</h3><div class="recipe-meta">${r.time} min • ${r.cal} kcal • ${r.p}g protein</div><small>${r.ingredients.join(' • ')}</small></div></button>`}
function fillDayRows(){const t=totals();if(!(state.profile.calorieGoal>0)||!(state.profile.proteinGoal>0))return `<div class="empty">Set your nutrition targets first so Fill My Day can use your real goals. <button class="secondary" data-action="editGoals">Set goals</button></div>`;const remP=Math.max(0,state.profile.proteinGoal-t.p);const remCal=Math.max(0,state.profile.calorieGoal-t.cal);const matches=recipeMatches({maxCal:remCal||Infinity,minProtein:Math.min(remP,20)}).slice(0,3);return `<div class="callout"><b>Veyra is matching your actual context.</b><br>You’ve logged ${t.cal} kcal and ${t.p}g protein. Remaining target: ~${remCal} kcal and ~${remP}g protein. It also considers ${esc(state.profile.diet||'your diet')}, your pantry and favorite cuisines.</div><div class="food-row"><span class="food-emoji">🎯</span><span><b>Current gap</b><small>~${remCal} kcal planned • ~${remP}g protein remaining</small></span></div>${matches.length?matches.map(r=>`<button class="food-row" data-recipe="${esc(r.name)}"><span class="food-emoji">${r.emoji}</span><span><b>${r.name}</b><small>${r.cuisine} • ${r.cal} kcal • ${r.p}g protein • pantry-aware</small></span><span>View ›</span></button>`).join(''):`<div class="empty">No current recipe matches every constraint. Add pantry items or loosen a filter rather than getting a fake recommendation.</div>`}`}

function pantryView(){return hero('Pantry Mode','Your kitchen, searchable.','Type ingredients, scan a photo for suggestions, then turn them into recipes without re-entering everything.',`<button class="primary" data-action="pantryCamera">📸 Scan pantry</button>`)+`<div class="card"><form id="pantryForm" class="inline-form"><input id="pantryInput" placeholder="Add an ingredient"><button class="primary">Add</button></form><div class="chip-list">${state.pantry.map((x,i)=>`<button class="chip" data-pantryremove="${i}">${esc(x)} ×</button>`).join('')}</div></div><div class="card" style="margin-top:16px"><div class="card-head"><h2>Recipe matches</h2><button class="ghost" data-route="recipes">See all</button></div><div class="recipe-grid">${recipeMatches().slice(0,3).map(recipeCard).join('')}</div></div>`}

function labView(){return hero('Veyra Lab','Run personal experiments carefully.','Explore patterns in your own logs with sample size and limitations visible. Correlation is not causation.',`<button class="primary" data-action="newExperiment">+ New experiment</button>`)+`${state.experiments.length?`<div class="grid grid-3">${state.experiments.map(e=>`<div class="card"><div class="card-head"><h2>${esc(e.name||'Personal experiment')}</h2></div><p class="muted">${esc(e.note||'Collecting your data.')}</p><div class="callout">Veyra shows associations only after enough observations exist.</div></div>`).join('')}</div>`:`<div class="card"><div class="empty"><b>No experiments yet.</b><br>Start one and Veyra will analyze only your real logs — no demo correlations.</div></div>`}`}

function sleepView(){const s=state.sleep.find(x=>x.date===today())||{hours:0,quality:3};return hero('Recovery','Sleep and readiness, kept simple.','Log sleep and how you feel. Veyra uses it as context — never as a diagnosis.',`<button class="primary" data-action="logSleep">Log sleep</button>`)+`<div class="grid grid-3">${plainMetric('☾','Sleep',s.hours?s.hours+' h':'Not logged','Today')}${plainMetric('🧠','Quality',s.hours?s.quality+'/5':'—','Optional check-in')}${plainMetric('🧘','Recovery logs',state.sleep.length,'All time')}</div><div class="card" style="margin-top:16px"><div class="card-head"><h2>Recovery insight</h2></div><p class="muted">When your sleep log is lower than your recent baseline, Veyra Coach can suggest keeping training flexible rather than forcing a harder session.</p></div>`}

function profileView(){const p=state.profile;const cuisines=(p.favoriteCuisines||[]);return hero('Your Profile',p.name?`Hi, ${esc(p.name)}.`:'Make Veyra yours.','This is the profile for the person using Veyra. Your creator information lives separately under About Creator.',`<button class="primary" data-action="editGoals">Edit profile & goals</button>`)+`
<div class="profile-dashboard"><div class="card user-profile-card"><div class="user-avatar">${esc((p.name||'?').charAt(0).toUpperCase())}</div><div><span class="eyebrow">LOCAL PROFILE</span><h2>${esc(p.name||'No name set')}</h2><p class="muted">${esc(p.goalText||'No personal goal added yet.')}</p><div class="chip-list">${p.diet?`<span class="chip">🥗 ${esc(p.diet)}</span>`:''}${p.trainingDays?`<span class="chip">🏋️ ${p.trainingDays} days/week</span>`:''}${p.sessionMinutes?`<span class="chip">⏱ ${p.sessionMinutes} min/session</span>`:''}${p.activityLevel?`<span class="chip">🚶 ${esc(p.activityLevel)} activity</span>`:''}</div></div></div>
<div class="card"><div class="card-head"><div><h2>Daily targets</h2><small>Tap Edit any time. These are never locked.</small></div><button class="secondary" data-action="editGoals">Edit targets</button></div><div class="target-list">${[['Calories',p.calorieGoal,'kcal'],['Protein',p.proteinGoal,'g'],['Carbs',p.carbGoal,'g'],['Fat',p.fatGoal,'g'],['Fiber',p.fiberGoal,'g'],['Water',p.waterGoal,p.units==='metric'?'mL':'oz']].map(([n,v,u])=>`<div class="target-row"><span>${n}</span><b>${v>0?fmt(v)+' '+u:'Not set'}</b><button class="tiny-edit" data-action="editGoals">Edit</button></div>`).join('')}</div></div>
<div class="card"><div class="card-head"><h2>Food preferences</h2><button class="secondary" data-action="editGoals">Edit</button></div><p class="muted"><b>Diet / restrictions:</b> ${esc([p.diet,...(p.dietaryRestrictions||[])].filter(Boolean).join(', ')||'Not set')}</p><p class="muted"><b>Favorite cuisines:</b> ${esc(cuisines.join(', ')||'Not set')}</p><p class="muted"><b>Foods to avoid:</b> ${esc(p.foodsAvoid||'None listed')}</p></div>
<div class="card"><div class="card-head"><h2>Veyra Vault</h2><small>Your portable local profile.</small></div><div class="stack-actions"><button class="secondary" data-action="export">Download my Veyra JSON</button><button class="secondary" data-action="import">Import Veyra JSON</button><button class="secondary" data-action="exportCSV">Export food history CSV</button></div><div class="callout">Moving phones or computers? Export here, then import the JSON on the other device. No account required.</div></div></div>`}

function dataView(){return hero('Public Data','Evidence, not decoration.','A small set of credible public benchmarks gives context without pretending population statistics are personal advice.')+`<div class="stat-strip public-data-grid"><div class="public-stat visual-stat"><span class="stat-icon">🌍</span><b>31%</b><small>of adults worldwide were insufficiently physically active in 2022.</small><a class="source-link" href="https://www.who.int/news-room/fact-sheets/detail/physical-activity" target="_blank" rel="noopener">WHO source ↗</a></div><div class="public-stat visual-stat"><span class="stat-icon">🏃</span><b>150 min</b><small>weekly moderate-intensity activity is a common adult public-health benchmark.</small><a class="source-link" href="https://www.cdc.gov/physical-activity-basics/guidelines/adults.html" target="_blank" rel="noopener">CDC source ↗</a></div><div class="public-stat visual-stat"><span class="stat-icon">🏋️</span><b>2 days</b><small>of muscle-strengthening activity per week is included in CDC adult guidance.</small><a class="source-link" href="https://www.cdc.gov/physical-activity-basics/guidelines/adults.html" target="_blank" rel="noopener">CDC source ↗</a></div></div><div class="card public-explainer"><div class="card-head"><h2>How Veyra uses public data</h2></div><p class="muted">Public statistics appear as context and methodology references. Veyra does not convert population averages into personalized medical claims. Your own profile, pantry, preferences, workouts and logs drive your in-app recommendations.</p></div>`}

function creatorView(){return hero('About the Creator','Built because tracking should feel useful, not exhausting.','Free, private and local-first — designed for everyday people who want nutrition, training and progress in one coherent place.')+`
<div class="card profile-hero"><img class="profile-photo" src="assets/shriyan.jpg" alt="Shriyan Avadhanula" onerror="this.src='assets/icon-512.png'"><div class="profile-copy"><div class="eyebrow">Creator</div><h1>Shriyan Avadhanula</h1><p class="muted">I built Veyra because I play competitive sports, train regularly, and wanted one place where food, workouts, recovery and progress actually connect. Existing trackers often felt fragmented, repetitive or locked behind subscriptions, so Veyra was designed to make the everyday flow simpler, more motivating and private.</p><p class="muted">Shriyan is a competitive pickleball athlete and student developer working across artificial intelligence, computer vision, cybersecurity and entrepreneurship. He created DinkSense, a local-first pickleball athlete-intelligence platform, co-founded ATHENA, and has built other independent technology projects.</p><div class="profile-links"><a class="primary link-btn" href="https://linkedin.com/in/shriyan-avadhanula" target="_blank" rel="noopener">LinkedIn ↗</a><a class="secondary link-btn" href="https://sribyju.github.io" target="_blank" rel="noopener">Projects ↗</a></div><p class="muted" style="margin-top:12px"><small>Contact: use LinkedIn or the project links above to reach the creator.</small></p><div class="resume-points"><div class="resume-point"><b>DinkSense</b><small>Local-first athlete-development platform with browser-based motion analysis and adaptive coaching.</small></div><div class="resume-point"><b>ATHENA</b><small>Athlete-intelligence research platform using uncertainty-aware athlete modeling and real-world validation.</small></div><div class="resume-point"><b>DataShadow</b><small>Personal-data monetization platform exploring privacy, adaptive intelligence and user control.</small></div><div class="resume-point"><b>Competitive athlete</b><small>4.5-rated junior singles pickleball player with brand sponsorship experience.</small></div></div></div></div>
<div class="card" style="margin-top:16px"><div class="card-head"><div><h2>Methodology & technical architecture</h2><small>For the people who want to know how it works.</small></div></div><div class="method-grid">${[
['Veyra Nexus','Combines nutrition, workouts, activity, sleep, pantry, preferences and history into contextual “next best action” suggestions.'],
['Local-first data','Logs and preferences stay in browser storage. Export/import provides portable backups without requiring an account.'],
['Veyra Lens','One capture flow for food, nutrition labels, pantry ingredients and activity screenshots. Detection is always confirmable/editable.'],
['Confidence Engine','Each AI/estimated entry carries confidence based on identification, portion and source certainty instead of pretending estimates are exact.'],
['Activity estimates','Reported/estimated calories are shown with uncertainty and are not treated as exact permission to eat a fixed amount more.'],
['Prediction','Trend projections are ranges based on recent history, clearly separated from observed data and never guaranteed.'],
['Veyra Replay','Searches the user’s own logs and patterns locally so history becomes useful instead of a static archive.'],
['Veyra Lab','Explores personal associations with sample sizes and limitations; it explicitly avoids causal claims from correlation.'],
['PWA','Manifest + service worker allow install-like use and offline access after first load on supported browsers.'],
['Spotify','The UI supports a workout-music integration path; full account authorization uses Spotify’s browser-safe PKCE flow and requires a registered Spotify client ID.'],
['Public data','Context cards use WHO and CDC sources and link directly to the originals.'],
['Responsibility & limits','Veyra and its creators provide tracking, estimates and educational guidance, not medical advice. Estimates can be wrong; users are responsible for how they use them.']
].map(x=>`<div class="method-card"><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('')}</div></div>
<div class="card" style="margin-top:16px"><div class="card-head"><h2>Sources</h2></div><p class="muted">WHO Physical Activity Fact Sheet • CDC Adult Physical Activity Guidelines • Dietary Guidelines for Americans • Open Food Facts for optional public barcode/product lookup • Spotify Developer documentation for PKCE authorization.</p><div class="profile-links"><a class="ghost link-btn" href="https://www.who.int/news-room/fact-sheets/detail/physical-activity" target="_blank" rel="noopener">WHO ↗</a><a class="ghost link-btn" href="https://www.cdc.gov/physical-activity-basics/guidelines/adults.html" target="_blank" rel="noopener">CDC ↗</a><a class="ghost link-btn" href="https://www.dietaryguidelines.gov/" target="_blank" rel="noopener">Dietary Guidelines ↗</a><a class="ghost link-btn" href="https://developer.spotify.com/documentation/web-api/tutorials/code-pkce-flow" target="_blank" rel="noopener">Spotify PKCE ↗</a></div></div>`}

function aboutView(){return hero('Methodology','How Veyra works.','Technical architecture and limitations are available here.')}

function settingsView(){return hero('Settings','Make Veyra yours.','Local preferences, data portability, appearance, integrations and install help.')+`
<div class="grid grid-2"><div class="card goal-settings-card"><div class="card-head"><div><h2>🎯 Your profile & goals</h2><small>Everything personal is editable and belongs to the current user.</small></div><button class="primary" data-action="editGoals">Guided edit</button></div><div class="callout">Fastest route: use <b>Profile</b> for your name, diet, favorite cuisines, restrictions, schedule and Veyra Vault. Use <b>Goals</b> at the top of any screen to reopen guided setup.</div><form id="profileForm" class="form-grid"><label>Name<input name="name" value="${esc(state.profile.name||'')}" placeholder="Optional"></label><label>Main goal<select name="goal"><option value="">Choose...</option>${[['performance','Sports / performance'],['strength','Build strength'],['endurance','Improve endurance'],['wellness','General wellness'],['maintain','Maintain routine'],['custom','Something else']].map(([v,l])=>`<option value="${v}" ${state.profile.goal===v?'selected':''}>${l}</option>`).join('')}</select></label><label style="grid-column:1/-1">In your own words<input name="goalText" value="${esc(state.profile.goalText||'')}" placeholder="e.g., get stronger, improve conditioning, feel more consistent"></label><label>Diet<select name="diet"><option value="">Choose...</option>${['vegetarian','vegan','pescatarian','omnivore','custom'].map(v=>`<option ${state.profile.diet===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Calories / day<input name="calorieGoal" type="number" min="0" value="${state.profile.calorieGoal??''}" placeholder="Set your target"></label><label>Protein (g)<input name="proteinGoal" type="number" min="0" value="${state.profile.proteinGoal??''}" placeholder="Set your target"></label><label>Carbs (g)<input name="carbGoal" type="number" min="0" value="${state.profile.carbGoal??''}" placeholder="Set your target"></label><label>Fat (g)<input name="fatGoal" type="number" min="0" value="${state.profile.fatGoal??''}" placeholder="Set your target"></label><label>Fiber (g)<input name="fiberGoal" type="number" min="0" value="${state.profile.fiberGoal??''}" placeholder="Set your target"></label><label>Water (oz)<input name="waterGoal" type="number" min="0" value="${state.profile.waterGoal??''}" placeholder="Set your target"></label><button class="primary" style="grid-column:1/-1">Save goals</button></form><div class="callout">You can change these anytime. Veyra uses the same target editor for every profile. Estimates and educational guidance are not medical advice.</div></div>
<div class="card"><div class="card-head"><h2>Data Vault</h2><small>Switch devices without an account.</small></div><div class="stack-actions"><button class="secondary" data-action="export">Export Veyra Vault (.json)</button><button class="secondary" data-action="import">Import Veyra Vault</button><button class="secondary" data-action="exportCSV">Export food log (.csv)</button><button class="ghost" data-action="clearData">Delete local data</button></div></div>
<div class="card"><div class="card-head"><h2>Connected Apps</h2></div>${spotifyPanel(true)}<div class="integration"><span>⌚</span><div><b>Watch / fitness app activity</b><small>No direct Apple/Samsung connection. Import a screenshot from Apple Fitness, Samsung Health, treadmill apps or similar.</small></div><button class="secondary" data-action="activityImport">Import</button></div></div>
<div class="card"><div class="card-head"><h2>Install Veyra</h2><button id="installHere" class="primary">Install</button></div><div class="guide-step"><span class="step-num"></span><div><b>iPhone / iPad</b><small>Open Veyra in Safari → Share → Add to Home Screen → Add.</small></div></div><div class="guide-step"><span class="step-num">A</span><div><b>Android</b><small>Open in Chrome → menu → Add to Home screen / Install app.</small></div></div><div class="guide-step"><span class="step-num">PC</span><div><b>Desktop</b><small>Chrome/Edge can show an install icon in the address bar when the site is served over HTTPS.</small></div></div></div>
<div class="card"><div class="card-head"><h2>Appearance & optional monetization</h2></div><div class="stack-actions"><button class="secondary" data-action="theme">Toggle light/dark</button><label class="switch-label"><input id="adsToggle" type="checkbox" ${state.settings.showAds?'checked':''}> Reserve AdSense placements</label><label class="switch-label"><input id="motionToggle" type="checkbox" ${state.settings.reducedMotion?'checked':''}> Reduce motion</label></div><div class="callout">Ad slots are intentionally hidden unless enabled. No ad script is bundled, so the app stays privacy-conscious by default.</div></div></div>`}

const views={today:todayView,food:foodView,train:trainView,progress:progressView,coach:coachView,profile:profileView,recipes:recipesView,pantry:pantryView,lab:labView,sleep:sleepView,data:dataView,creator:creatorView,about:aboutView,settings:settingsView};

function spotifyPanel(full=false){
  if(state.spotify.connected){const n=state.spotify.nowPlaying||{},track=n.track||'',artist=n.artist||'',playing=!!n.isPlaying;return `<div class="spotify-integration"><div class="integration"><span class="spotify-logo">●</span><div><b>${esc(state.spotify.displayName||'Spotify connected')}</b><small>${track?`${esc(track)}${artist?' • '+esc(artist):''}`:'Connected • refresh to see current playback'}</small></div><button class="secondary compact" data-spotify-action="refresh">↻</button><button class="secondary compact" data-action="spotifyDisconnect">Disconnect</button></div><div class="spotify-controls"><button class="ghost compact" data-spotify-action="previous" aria-label="Previous Spotify track">⏮</button><button class="primary compact" data-spotify-action="${playing?'pause':'play'}" aria-label="${playing?'Pause':'Play'} Spotify">${playing?'❚❚':'▶'}</button><button class="ghost compact" data-spotify-action="next" aria-label="Next Spotify track">⏭</button><a class="secondary compact button-link" href="https://open.spotify.com" target="_blank" rel="noopener">Open Spotify ↗</a></div>${full?'<small class="muted">Playback controls depend on Spotify account/device availability. Veyra never stores your Spotify password.</small>':''}</div>`}
  return `<div class="integration"><span class="spotify-logo">●</span><div><b>Spotify</b><small>${full?'Connect with browser-safe PKCE after adding your Spotify app Client ID.':'Bring workout music into Veyra Live.'}</small></div><button class="secondary" data-action="spotifyConnect">Connect</button></div>`}

function bind(){
  $$('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));
  $$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
  $$('[data-spotify-action]').forEach(b=>b.onclick=()=>spotifyPlayback(b.dataset.spotifyAction));
  $$('[data-edit]').forEach(b=>b.onclick=()=>editItem(b.dataset.edit));
  $$('[data-mealadd]').forEach(b=>b.onclick=()=>addFoodModal(b.dataset.mealadd));
  $$('[data-saved]').forEach(b=>b.onclick=()=>logSaved(b.dataset.saved));
  $$('[data-routine]').forEach(b=>b.onclick=()=>startWorkout(b.dataset.routine));
  $$('[data-chart]').forEach(b=>b.onclick=()=>{$$('[data-chart]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#mainChart').innerHTML=chartSVG(b.dataset.chart)});
  $$('[data-recipe]').forEach(b=>b.onclick=()=>openRecipe(b.dataset.recipe));
  $$('[data-pantryremove]').forEach(b=>b.onclick=()=>{state.pantry.splice(+b.dataset.pantryremove,1);save();render()});
  $$('.coach-prompt').forEach(b=>b.onclick=()=>{const i=$('#coachInput');if(i){i.value=b.textContent;$('#coachForm').requestSubmit()}});
  $('#coachForm')?.addEventListener('submit',e=>{e.preventDefault();chat($('#coachInput').value);$('#coachInput').value=''});
  $('#pantryForm')?.addEventListener('submit',e=>{e.preventDefault();const v=$('#pantryInput').value.trim();if(v){state.pantry.push(v);save();render()}});
  $('#profileForm')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);for(const [k,v] of fd){state.profile[k]=['calorieGoal','proteinGoal','carbGoal','fatGoal','fiberGoal','waterGoal'].includes(k)?(v===''?null:+v):v}state.onboardingComplete=['calorieGoal','proteinGoal','carbGoal','fatGoal'].some(k=>state.profile[k]>0)||!!state.profile.goal||!!state.profile.goalText;state.onboardingSkipped=false;save();render();toast('Goals saved')});
  $('#advancedToggle')?.addEventListener('change',e=>{state.settings.advancedNutrition=e.target.checked;save();render()});
  $('#adsToggle')?.addEventListener('change',e=>{state.settings.showAds=e.target.checked;save();toast('Ad placement preference saved')});
  $('#motionToggle')?.addEventListener('change',e=>{state.settings.reducedMotion=e.target.checked;document.documentElement.classList.toggle('reduce-motion',e.target.checked);save()});
  $('#installHere')?.addEventListener('click',installApp);
}

function action(a){({editGoals:openOnboarding,quickAdd:quickAddModal,lens:()=>lens('food'),voice:startVoice,fillDay:()=>go('recipes'),activityImport:()=>lens('activity'),pantryCamera:()=>lens('pantry'),replay:replayModal,water:waterModal,sleep:()=>go('sleep'),startWorkout:()=>startWorkout(),progress:()=>go('progress'),recipes:()=>go('recipes'),addFood:()=>addFoodModal(),saveCurrentMeal:saveCurrentMeal,addRoutine:addRoutineModal,weeklyReport:weeklyReport,newExperiment:newExperiment,logSleep:logSleepModal,export:exportVault,import:()=>$('#backupInput').click(),exportCSV,clearData,theme:toggleTheme,spotifyConnect:spotifyConnect,spotifyDisconnect:spotifyDisconnect,restaurant:restaurantModal,flexDay:flexDayModal,recipeCalc:recipeCalcModal}[a]||(()=>{}))()}

function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').hidden=false;setTimeout(()=>$('#modalBody input, #modalBody button')?.focus(),30)}
function closeModal(){$('#modal').hidden=true;if(restTimer)clearInterval(restTimer)}
function quickAddModal(){openModal('Quick add',`<div class="quick-actions modal-quick">${quick('🍴','Food','Search or type','addFood')}${quick('📸','Lens','Photo / screenshot','lens')}${quick('🏋️','Workout','Start routine','startWorkout')}${quick('🏃','Activity','Manual activity','activityManual')}${quick('💧','Water','Add hydration','water')}${quick('☾','Sleep','Recovery log','logSleep')}</div>`);$$('#modalBody [data-action]').forEach(b=>b.onclick=()=>{closeModal();if(b.dataset.action==='activityManual')activityManual();else action(b.dataset.action)})}
function addFoodModal(meal='Snack',existing=null){const x=existing||{name:'',cal:'',p:'',c:'',f:'',fiber:'',sugar:'',meal,time:now().toTimeString().slice(0,5),confidence:95};openModal(existing?'Edit meal':'Log food',`<form id="foodForm" class="form-grid"><label style="grid-column:1/-1">Food or meal<input name="name" value="${esc(x.name)}" placeholder="e.g., MorningStar crumbles" required></label><label>Meal<select name="meal">${['Breakfast','Lunch','Dinner','Snack'].map(m=>`<option ${m===x.meal?'selected':''}>${m}</option>`).join('')}</select></label><label>Time<input name="time" type="time" value="${x.time}"></label><label>Calories<input name="cal" type="number" value="${x.cal}" required></label><label>Protein (g)<input name="p" type="number" value="${x.p}" required></label><label>Carbs (g)<input name="c" type="number" value="${x.c||0}"></label><label>Fat (g)<input name="f" type="number" value="${x.f||0}"></label><label>Fiber (g)<input name="fiber" type="number" value="${x.fiber||0}"></label><label>Sugar (g)<input name="sugar" type="number" value="${x.sugar||0}"></label><label style="grid-column:1/-1">Serving / notes<input name="notes" placeholder="1 serving, 120 g, etc." value="${esc(x.notes||'')}"></label><button class="primary" style="grid-column:1/-1">${existing?'Save changes':'Log food'}</button>${existing?'<button type="button" id="deleteMeal" class="ghost" style="grid-column:1/-1">Delete entry</button>':''}</form><div class="callout">Tip: search packaged foods with the barcode scanner or type a brand/product. Veyra keeps edits available at all times.</div>`);$('#foodForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const obj={...x,...d,id:x.id||uid(),date:today(),cal:+d.cal,p:+d.p,c:+d.c,f:+d.f,fiber:+d.fiber,sugar:+d.sugar,confidence:x.confidence||95,source:x.source||'manual'};if(existing)state.meals[state.meals.findIndex(m=>m.id===x.id)]=obj;else state.meals.push(obj);touchStreak();save();closeModal();render();toast(existing?'Meal updated':'Food logged')};$('#deleteMeal')?.addEventListener('click',()=>{state.meals=state.meals.filter(m=>m.id!==x.id);save();closeModal();render();toast('Entry deleted')})}
function editItem(s){const [kind,id]=s.split(':');if(kind==='meal'){const x=state.meals.find(m=>m.id===id);if(x)addFoodModal(x.meal,x)}else{const x=state.activities.find(a=>a.id===id);if(x)activityManual(x)}}
function logSaved(name){const x=state.savedMeals.find(s=>s.name===name);if(!x)return;state.meals.push({...x,id:uid(),date:today(),time:now().toTimeString().slice(0,5),meal:'Snack',confidence:99,source:'saved meal'});touchStreak();save();render();toast(`${name} logged`)}

function lens(mode='food'){window._lensMode=mode;$('#imageInput').click()}
async function processImage(file){const mode=window._lensMode||'food';const url=URL.createObjectURL(file);openModal(mode==='activity'?'Import activity screenshot':mode==='pantry'?'Scan ingredients':'Veyra Lens',`<img class="scan-preview" src="${url}" alt="Uploaded image"><div class="scan-status"><span class="spinner"></span> Analyzing locally where your browser allows…</div>`);let text='';try{if('TextDetector'in window){const det=new TextDetector();const bmp=await createImageBitmap(file);const blocks=await det.detect(bmp);text=blocks.map(b=>b.rawValue).join(' ');}}catch{}
setTimeout(()=>{if(mode==='activity')activityDetected(url,text,file.name);else if(mode==='pantry')pantryDetected(url,text,file.name);else foodDetected(url,text,file.name)},700)}
function foodDetected(url,text,name){
  const cue=((text||'')+' '+(name||'')).trim();
  $('#modalBody').innerHTML=`<img class="scan-preview" src="${url}"><div class="detect-head"><div><h3>Review this food photo</h3><small>Veyra will not invent nutrition from an uncertain image.</small></div><span class="confidence">Needs confirmation</span></div><div class="callout">If Smart Vision is unavailable, enter or confirm the food name and nutrition from a label, restaurant listing, or another source before logging.</div><div class="stack-actions"><button id="editDetected" class="primary">Enter / review food</button><button id="labelMode" class="secondary">This is a nutrition label</button><button id="barcodeMode" class="secondary">Scan barcode instead</button></div>`;
  $('#editDetected').onclick=()=>{closeModal();addFoodModal('Snack',{name:cue&&cue.length<80?cue:'',cal:'',p:'',c:'',f:'',fiber:'',sugar:'',time:now().toTimeString().slice(0,5),meal:'Snack',confidence:40,source:'photo — manual confirmation required'});};
  $('#labelMode').onclick=()=>labelDetected(url,text);$('#barcodeMode').onclick=()=>barcodeFromImage();
}
function labelDetected(url,text){const nums=(text.match(/\d+(?:\.\d+)?/g)||[]).map(Number);const guess={name:'Custom label food',cal:nums[0]||200,p:nums.find(n=>n>5&&n<80)||15,c:25,f:8,fiber:3,sugar:5,confidence:text?82:55,time:now().toTimeString().slice(0,5),meal:'Snack',source:'label scan'};closeModal();addFoodModal('Snack',guess)}
function pantryDetected(url,text,name){const words=(text||name).toLowerCase();const guesses=['spinach','rice','black beans','tortillas','yogurt','cheese','peppers'].filter(x=>words.includes(x.split(' ')[0]));const list=guesses.length?guesses:['spinach','rice','beans','vegetables'];$('#modalBody').innerHTML=`<img class="scan-preview" src="${url}"><h3>Possible ingredients</h3><div class="chip-list">${list.map(x=>`<label class="chip"><input type="checkbox" value="${x}" checked> ${x}</label>`).join('')}</div><div class="callout">Generic browser vision cannot reliably identify every ingredient or quantity. Veyra treats these as suggestions and asks you to confirm.</div><button id="pantryConfirm" class="primary">Add selected & show recipes</button>`;$('#pantryConfirm').onclick=()=>{$$('#modalBody input:checked').forEach(i=>{if(!state.pantry.includes(i.value))state.pantry.push(i.value)});save();closeModal();go('recipes')}}
function activityDetected(url,text,name){const s=(text+' '+name).toLowerCase();const nums=(text.match(/\d+(?:\.\d+)?/g)||[]).map(Number);let type=s.includes('run')?'Run':s.includes('walk')?'Walk':s.includes('cycle')?'Cycling':'Imported workout';let duration=nums.find(n=>n>=5&&n<=300)||30;let calories=nums.find(n=>n>=60&&n<=2000)||250;let distance=s.includes('mi')?(nums.find(n=>n>0&&n<50)||0):0;$('#modalBody').innerHTML=`<img class="scan-preview" src="${url}"><div class="detect-head"><div><h3>${type}</h3><small>From screenshot • confirm before saving</small></div><span class="confidence">${text?86:62}% confidence</span></div><form id="activityImportForm" class="form-grid"><label>Activity<input name="type" value="${type}"></label><label>Duration (min)<input name="duration" type="number" value="${duration}"></label><label>Distance<input name="distance" type="number" step=".01" value="${distance}"></label><label>Reported calories<input name="calories" type="number" value="${calories}"></label><button class="primary" style="grid-column:1/-1">Add to today</button></form><div class="callout">Imported calorie-burn values are kept as reported/estimated and shown separately from food intake. They are not treated as exact “extra calories to eat.”</div>`;$('#activityImportForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));state.activities.push({id:uid(),date:today(),time:now().toTimeString().slice(0,5),type:d.type,duration:+d.duration,distance:+d.distance,calories:+d.calories,source:'screenshot import',confidence:text?86:62});touchStreak();save();closeModal();render();toast('Activity imported')}}
async function barcodeFromImage(){closeModal();openModal('Barcode lookup',`<form id="barcodeForm" class="inline-form"><input name="code" inputmode="numeric" placeholder="Enter barcode number" required><button class="primary">Look up</button></form><div class="callout">If your browser supports live BarcodeDetector, Veyra can use it from camera images; manual barcode entry is the reliable fallback. Product data comes from Open Food Facts when online.</div>`);$('#barcodeForm').onsubmit=async e=>{e.preventDefault();const code=new FormData(e.currentTarget).get('code');try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json`);const j=await r.json();if(!j.product)throw Error();const p=j.product,n=p.nutriments||{};closeModal();addFoodModal('Snack',{name:p.product_name||'Barcode food',cal:Math.round(n['energy-kcal_100g']||n['energy-kcal']||0),p:Math.round(n.proteins_100g||0),c:Math.round(n.carbohydrates_100g||0),f:Math.round(n.fat_100g||0),fiber:Math.round(n.fiber_100g||0),sugar:Math.round(n.sugars_100g||0),time:now().toTimeString().slice(0,5),meal:'Snack',confidence:95,source:'Open Food Facts'});}catch{toast('Product not found — add it manually')}}}


function flexDayModal(){openModal('Flexible Day',`<p class="muted">Choose how structured you want today to feel. Veyra adapts suggestions without labeling food as “good” or “bad.”</p><div class="stack-actions"><button class="secondary flex-choice" data-mode="normal">Normal plan</button><button class="secondary flex-choice" data-mode="flexible">More flexible today</button><button class="secondary flex-choice" data-mode="celebration">Celebration / eating out</button></div>`);$$('.flex-choice').forEach(b=>b.onclick=()=>{state.dayMode=state.dayMode||{};state.dayMode[today()]=b.dataset.mode;save();closeModal();toast(`Today set to ${b.textContent}`)})}
function restaurantModal(){const t=totals(),remP=Math.max(0,state.profile.proteinGoal-t.p);openModal('Restaurant intelligence',`<form id="restaurantForm" class="inline-form"><input name="place" placeholder="Restaurant or cuisine — e.g., Chipotle"><button class="primary">Build options</button></form><div id="restaurantResults" class="command-results"><div class="callout">Veyra can rank choices around dietary restrictions and what you have already logged. Nutrition should be confirmed against the restaurant’s current published information when available.</div></div>`);$('#restaurantForm').onsubmit=e=>{e.preventDefault();const place=new FormData(e.currentTarget).get('place');$('#restaurantResults').innerHTML=[`Vegetarian protein-forward option • aim to include beans/tofu/other protein source`,`Higher-fiber option • add vegetables/beans where available`,`Flexible option • choose what sounds good, then log the published nutrition if available`].map((x,i)=>`<button class="command-result"><b>${esc(place)} option ${i+1}</b><br><small>${x} • about ${remP}g protein remains in your current target</small></button>`).join('')}}
function recipeCalcModal(){openModal('Recipe calculator',`<form id="recipeCalcForm" class="form-grid"><label style="grid-column:1/-1">Recipe name<input name="name" placeholder="Protein pasta" required></label><label>Total calories<input name="cal" type="number" placeholder="1800" required></label><label>Total protein (g)<input name="p" type="number" placeholder="120" required></label><label>Total carbs (g)<input name="c" type="number" placeholder="220"></label><label>Total fat (g)<input name="f" type="number" placeholder="50"></label><label>Servings<input name="servings" type="number" value="6" min="1" required></label><button class="primary" style="grid-column:1/-1">Calculate & save</button></form><div id="recipeCalcOut"></div>`);$('#recipeCalcForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const n=Math.max(1,+d.servings),item={name:d.name,cal:Math.round(+d.cal/n),p:Math.round(+d.p/n),c:Math.round((+d.c||0)/n),f:Math.round((+d.f||0)/n),fiber:0,sugar:0};state.savedMeals.push(item);save();$('#recipeCalcOut').innerHTML=`<div class="callout"><b>Per serving:</b> ${item.cal} kcal • ${item.p}g protein • ${item.c}g carbs • ${item.f}g fat. Saved to your meals.</div>`}}

function activityManual(existing=null){const x=existing||{type:'Run',duration:'',distance:'',calories:'',time:now().toTimeString().slice(0,5)};openModal(existing?'Edit activity':'Log activity',`<form id="activityForm" class="form-grid"><label>Activity<input name="type" value="${esc(x.type)}"></label><label>Time<input name="time" type="time" value="${x.time}"></label><label>Duration (min)<input name="duration" type="number" value="${x.duration}"></label><label>Distance<input name="distance" type="number" step=".1" value="${x.distance||0}"></label><label>Estimated/reported calories<input name="calories" type="number" value="${x.calories||0}"></label><button class="primary" style="grid-column:1/-1">Save</button>${existing?'<button type="button" id="deleteActivity" class="ghost" style="grid-column:1/-1">Delete</button>':''}</form>`);$('#activityForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const obj={...x,...d,id:x.id||uid(),date:today(),duration:+d.duration,distance:+d.distance,calories:+d.calories,source:x.source||'manual',confidence:x.confidence||75};if(existing)state.activities[state.activities.findIndex(a=>a.id===x.id)]=obj;else state.activities.push(obj);touchStreak();save();closeModal();render()};$('#deleteActivity')?.addEventListener('click',()=>{state.activities=state.activities.filter(a=>a.id!==x.id);save();closeModal();render()})}
function waterModal(){openModal('Hydration',`<div class="rest-clock">${state.water[today()]||0}<small> oz</small></div><div class="quick-actions">${[8,12,16,24].map(n=>`<button class="quick-card water-add" data-oz="${n}"><span class="quick-icon">💧</span><b>+${n} oz</b></button>`).join('')}</div>`);$$('.water-add').forEach(b=>b.onclick=()=>{state.water[today()]=(state.water[today()]||0)+(+b.dataset.oz);save();closeModal();render();toast('Water logged')})}
function logSleepModal(){openModal('Log sleep',`<form id="sleepForm" class="form-grid"><label>Hours<input name="hours" type="number" min="0" max="16" step=".25" value="7.5"></label><label>Quality (1–5)<input name="quality" type="number" min="1" max="5" value="4"></label><button class="primary" style="grid-column:1/-1">Save</button></form>`);$('#sleepForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));state.sleep=state.sleep.filter(x=>x.date!==today());state.sleep.push({id:uid(),date:today(),hours:+d.hours,quality:+d.quality});save();closeModal();render();toast('Sleep logged')}}

function startWorkout(id='push'){const routine=state.routines.find(r=>r.id===id)||state.routines[0];liveWorkout={id:uid(),routine:routine.name,start:Date.now(),exercises:routine.exercises.map(e=>({...e,done:false,setsData:Array.from({length:e.sets},()=>({done:false,weight:'',reps:'',seconds:e.kind==='time'?45:''}))}))};renderLiveWorkout()}
function renderLiveWorkout(){const w=liveWorkout;openModal(w.routine,`<div class="live-top"><div><span class="confidence">LIVE</span><h3>${w.routine}</h3></div><div class="live-elapsed" id="elapsed">00:00</div></div><div class="workout-live"><div><div class="exercise-live-list">${w.exercises.map((e,ei)=>`<div class="exercise-live ${e.done?'done':''}"><div class="exercise-live-head"><span class="exercise-visual">${e.icon}</span><div><b>${e.name}</b><small>${e.muscle} • ${e.kind==='time'?'Timed':'Reps'} • target ${e.target}</small></div><button class="set-check ${e.done?'done':''}" data-exdone="${ei}">${e.done?'✓':'○'}</button></div><table class="sets-table"><thead><tr><th>Set</th>${e.kind==='time'?'<th>Seconds</th>':'<th>Weight</th><th>Reps</th>'}<th>Done</th></tr></thead><tbody>${e.setsData.map((s,si)=>`<tr><td>${si+1}</td>${e.kind==='time'?`<td><input data-field="seconds" data-ei="${ei}" data-si="${si}" type="number" value="${s.seconds}"></td>`:`<td><input data-field="weight" data-ei="${ei}" data-si="${si}" inputmode="decimal" value="${s.weight}" placeholder="—"></td><td><input data-field="reps" data-ei="${ei}" data-si="${si}" inputmode="numeric" value="${s.reps}" placeholder="—"></td>`}<td><button class="set-check ${s.done?'done':''}" data-setdone="${ei}:${si}">${s.done?'✓':'○'}</button></td></tr>`).join('')}</tbody></table><div class="exercise-actions"><button class="ghost" data-substitute="${ei}">Substitute</button><button class="ghost" data-noteexercise="${ei}">Note</button></div></div>`).join('')}</div></div><aside><div class="card flat"><div class="card-head"><h3>Rest</h3><small>Auto after a set</small></div><div class="rest-clock" id="restClock">0:00</div><div class="quick-actions">${[30,60,90].map(n=>`<button class="quick-card rest-start" data-sec="${n}"><b>${n}s</b></button>`).join('')}</div></div><div class="card flat spotify-card" style="margin-top:10px">${spotifyPanel()}</div><button id="finishWorkout" class="primary full" style="margin-top:10px">Finish workout</button></aside></div>`);
const tick=()=>{const s=Math.floor((Date.now()-w.start)/1000);const el=$('#elapsed');if(el)el.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};tick();const elapsedInt=setInterval(tick,1000);
$$('[data-setdone]').forEach(b=>b.onclick=()=>{const [ei,si]=b.dataset.setdone.split(':').map(Number);const s=w.exercises[ei].setsData[si];s.done=!s.done;b.classList.toggle('done',s.done);b.textContent=s.done?'✓':'○';if(s.done)startRest(60)});$$('[data-field]').forEach(i=>i.oninput=()=>{w.exercises[+i.dataset.ei].setsData[+i.dataset.si][i.dataset.field]=i.value});$$('[data-exdone]').forEach(b=>b.onclick=()=>{const e=w.exercises[+b.dataset.exdone];e.done=!e.done;renderLiveWorkout()});$$('.rest-start').forEach(b=>b.onclick=()=>startRest(+b.dataset.sec));$$('[data-substitute]').forEach(b=>b.onclick=()=>toast('Substitution picker: choose a movement for the same muscle group.'));$$('[data-noteexercise]').forEach(b=>b.onclick=()=>{const note=prompt('Exercise note');if(note)w.exercises[+b.dataset.noteexercise].note=note});$('#finishWorkout').onclick=()=>{clearInterval(elapsedInt);finishWorkout()};$$('#modalBody [data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));}
function startRest(sec){restRemaining=sec;clearInterval(restTimer);const draw=()=>{const e=$('#restClock');if(e)e.textContent=`${Math.floor(restRemaining/60)}:${String(restRemaining%60).padStart(2,'0')}`};draw();restTimer=setInterval(()=>{restRemaining--;draw();if(restRemaining<=0){clearInterval(restTimer);toast('Rest complete')}},1000)}
function finishWorkout(){if(!liveWorkout)return;const mins=Math.max(1,Math.round((Date.now()-liveWorkout.start)/60000));state.workouts.push({...liveWorkout,date:today(),duration:mins});state.activities.push({id:uid(),date:today(),time:now().toTimeString().slice(0,5),type:liveWorkout.routine,duration:mins,distance:0,calories:Math.round(mins*5.5),source:'Veyra Live estimate',confidence:70});liveWorkout=null;touchStreak();save();closeModal();render();toast('Workout saved')}

function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){openModal('Voice',`<div class="callout">Speech recognition isn’t available in this browser. Use the command box or your phone keyboard’s microphone — the same natural-language parser still works.</div><form id="voiceFallback" class="inline-form"><input name="text" placeholder="I ate… / I ran… / start push day"><button class="primary">Go</button></form>`);$('#voiceFallback').onsubmit=e=>{e.preventDefault();const t=new FormData(e.currentTarget).get('text');closeModal();handleCommand(t)};return}const r=new SR();r.lang='en-US';r.interimResults=false;openModal('Listening…',`<div class="voice-orb">🎙️</div><p class="center muted">Say “I ate…”, “start Push Day”, “I ran for 30 minutes”, “log 12 ounces of water”, or ask Veyra a question.</p>`);r.onresult=e=>{const t=e.results[0][0].transcript;closeModal();toast(`Heard: ${t}`);handleCommand(t)};r.onerror=()=>{closeModal();toast('Voice input ended')};r.start()}
function handleCommand(text){const s=text.toLowerCase();if(s.includes('start')&&(s.includes('push')||s.includes('workout')))return startWorkout(s.includes('pull')?'pull':s.includes('leg')?'legs':'push');if(s.includes('water')){const n=+(s.match(/\d+/)||[12])[0];state.water[today()]=(state.water[today()]||0)+n;save();render();return toast(`${n} oz water logged`)}if(s.match(/ran|run|walk|cycled|bike/)){const n=+(s.match(/\d+/)||[30])[0];return activityManual({type:s.includes('walk')?'Walk':s.includes('bike')||s.includes('cycle')?'Cycling':'Run',duration:n,distance:0,calories:'',time:now().toTimeString().slice(0,5),source:'voice — confirm activity details'})}if(s.includes('ate')||s.includes('had ')){const name=text.replace(/.*?(ate|had)\s+/i,'');return addFoodModal('Snack',{name,cal:0,p:0,c:0,f:0,fiber:0,sugar:0,time:now().toTimeString().slice(0,5),meal:'Snack',confidence:60,source:'voice — needs nutrition confirmation'})}if(s.includes('progress'))return go('progress');openCoachWith(text)}
function openCoachWith(text){go('coach');setTimeout(()=>{const i=$('#coachInput');if(i){i.value=text;$('#coachForm').requestSubmit()}},100)}
function chat(q){if(!q.trim())return;const log=$('#chatLog');log.insertAdjacentHTML('beforeend',`<div class="bubble user">${esc(q)}</div>`);const a=coachAnswer(q);setTimeout(()=>{log.insertAdjacentHTML('beforeend',`<div class="bubble bot"><b>Veyra Coach</b><br>${a}</div>`);log.scrollTop=log.scrollHeight},220)}
function coachAnswer(q){const s=q.toLowerCase(),t=totals();if(s.includes('eat today')||s.includes('ate today'))return state.meals.filter(x=>x.date===today()).map(x=>`${esc(x.name)} (${x.cal} kcal, ${x.p}g protein)`).join('<br>')||'Nothing is logged yet.';if(s.includes('protein')&&!s.includes('meal'))return state.profile.proteinGoal>0?`Today you’ve logged <b>${t.p}g</b> protein against your ${state.profile.proteinGoal}g target, leaving about <b>${Math.max(0,state.profile.proteinGoal-t.p)}g</b>.`:`You’ve logged <b>${t.p}g</b> protein today. Set a personal protein target in Goals if you want Veyra to track the gap.`;if(s.includes('push')){setTimeout(()=>startWorkout('push'),400);return 'Opening your Push Day in Veyra Live.'}if(s.includes('muscle'))return state.workouts.length?'Open Train → Muscle Map to see which muscle groups your actual logged workouts have covered.':'You do not have enough workout history for a muscle-coverage pattern yet.';if(s.includes('progress'))return 'Open Progress for Today, Week, Month, YTD, All Time and Predictive views. Predictions are clearly separated from observed data.';const asksFood=s.includes('what should i eat')||s.includes('eat next')||s.includes('meal')||s.includes('pantry')||s.includes('make');if(asksFood){const maxMatch=s.match(/(?:under|below|max(?:imum)?)[^\d]{0,8}(\d{2,4})\s*(?:cal|kcal|calories)?/i);const maxCal=maxMatch?+maxMatch[1]:(state.profile.calorieGoal>0?Math.max(0,state.profile.calorieGoal-t.cal):Infinity);const gap=state.profile.proteinGoal>0?Math.max(0,state.profile.proteinGoal-t.p):0;const explicitDiet=['vegetarian','vegan','pescatarian'].find(d=>s.includes(d));const matches=recipeMatches({maxCal:maxCal||Infinity,minProtein:gap?Math.min(gap,20):0,diet:explicitDiet||state.profile.diet});if(!matches.length)return `I couldn't find a recipe that honestly matches all of those constraints from the current recipe library and your pantry. Try adding pantry items or changing one limit.`;const r=matches[0];const pantryHits=r.ingredients.filter(i=>state.pantry.some(p=>i.toLowerCase().includes(p.toLowerCase().split(' ')[0])||p.toLowerCase().includes(i.toLowerCase().split(' ')[0]))).length;return `<b>${r.name}</b> is my best current match: ${r.cal} kcal, ${r.p}g protein, ${r.cuisine}. ${gap?`You have about ${gap}g protein left today. `:''}${Number.isFinite(maxCal)?`You asked/need to stay around ${maxCal} kcal. `:''}${explicitDiet||state.profile.diet?`Diet filter: ${esc(explicitDiet||state.profile.diet)}. `:''}${pantryHits?`${pantryHits} ingredient${pantryHits===1?'':'s'} match your pantry.`:'Add pantry items to make this even more specific.'}`}return 'I can combine your goals, remaining nutrition, dietary preferences, favorite cuisines, pantry, workouts, sleep and history. Try: “I want a vegetarian meal under 500 calories that helps me close my protein gap using my pantry.”'}
function saveCurrentMeal(){const arr=state.meals.filter(x=>x.date===today());if(!arr.length)return toast('Log food first');const x=arr.at(-1);state.savedMeals.push({name:x.name,cal:x.cal,p:x.p,c:x.c,f:x.f,fiber:x.fiber,sugar:x.sugar});save();render();toast('Saved meal')}
function openRecipe(name){const r=recipeMatches().find(x=>x.name===name);if(!r)return;openModal(name,`<div class="recipe-hero">${r.emoji}</div><p><b>${r.time} min • ${r.cal} kcal • ${r.p}g protein</b></p><h3>Ingredients</h3><div class="chip-list">${r.ingredients.map(i=>`<span class="chip">${i}</span>`).join('')}</div><h3>Simple method</h3><ol class="muted"><li>Prep the ingredients and portion them to preference.</li><li>Cook or assemble as appropriate.</li><li>Adjust seasoning and serving size.</li></ol><button id="cookLog" class="primary full">Cook this & log</button>`);$('#cookLog').onclick=()=>{state.meals.push({id:uid(),date:today(),time:now().toTimeString().slice(0,5),name:r.name,meal:'Dinner',cal:r.cal,p:r.p,c:45,f:14,fiber:9,sugar:6,source:'Veyra recipe',confidence:88});save();closeModal();render();toast('Recipe logged')}}

function configuredSpotifyClientId(){return String(window.VEYRA_CONFIG?.spotifyClientId||'').trim()}
function spotifyConnect(){const configured=configuredSpotifyClientId();if(configured&&state.spotify.clientId!==configured){state.spotify.clientId=configured;save()}if(!state.spotify.clientId){openModal('Spotify needs one publisher setting',`<div class="fi-question"><span>🎵</span><div><span class="eyebrow">ONE-TIME SITE OWNER SETUP</span><h2>Spotify is ready for PKCE</h2><p>Ordinary Veyra users should never need to paste a developer ID. The site owner only needs to register Veyra once and place the public Spotify Client ID in <code>config.js</code>.</p></div></div><div class="callout"><b>Redirect URI</b><br><code>https://sribyju.github.io/Veyra/</code><br><br>No client secret belongs in this GitHub Pages app.</div><details style="margin-top:12px"><summary>Developer/testing override on this device</summary><form id="spotifySetup" class="form-grid" style="margin-top:10px"><label style="grid-column:1/-1">Spotify Client ID<input name="clientId" placeholder="Public Client ID" required></label><button class="primary" style="grid-column:1/-1">Save locally & connect</button></form></details>`);$('#spotifySetup')?.addEventListener('submit',e=>{e.preventDefault();state.spotify.clientId=new FormData(e.currentTarget).get('clientId').trim();save();closeModal();beginSpotifyPKCE()});return}beginSpotifyPKCE()}
function spotifyB64(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function spotifyAuthorizationRequest(){const verifier=spotifyB64(crypto.getRandomValues(new Uint8Array(32)));const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=spotifyB64(new Uint8Array(digest)),redirect=location.origin+location.pathname;const u=new URL('https://accounts.spotify.com/authorize');u.search=new URLSearchParams({client_id:state.spotify.clientId,response_type:'code',redirect_uri:redirect,code_challenge_method:'S256',code_challenge:challenge,scope:'user-read-private user-read-email user-read-currently-playing user-read-playback-state user-modify-playback-state'});return {url:u.toString(),verifier,redirect,challenge}}
async function beginSpotifyPKCE(){const auth=await spotifyAuthorizationRequest();sessionStorage.setItem('spotify_verifier',auth.verifier);sessionStorage.setItem('spotify_redirect',auth.redirect);location.href=auth.url}
async function spotifyRefreshToken(){if(!state.spotify.refreshToken||!state.spotify.clientId)return false;try{const body=new URLSearchParams({client_id:state.spotify.clientId,grant_type:'refresh_token',refresh_token:state.spotify.refreshToken});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await r.json();if(!j.access_token)throw Error('token');state.spotify.accessToken=j.access_token;if(j.refresh_token)state.spotify.refreshToken=j.refresh_token;state.spotify.tokenExpiresAt=Date.now()+(Number(j.expires_in)||3600)*1000-60000;state.spotify.connected=true;save();return true}catch{return false}}
async function spotifyEnsureToken(){if(!state.spotify.connected||!state.spotify.accessToken)return false;if(!state.spotify.tokenExpiresAt||Date.now()<state.spotify.tokenExpiresAt)return true;return spotifyRefreshToken()}
async function spotifyRefreshNowPlaying(silent=false){if(!(await spotifyEnsureToken())){if(!silent)toast('Reconnect Spotify to refresh playback');return null}try{const r=await fetch('https://api.spotify.com/v1/me/player/currently-playing',{headers:{Authorization:`Bearer ${state.spotify.accessToken}`}});if(r.status===204){state.spotify.nowPlaying=null;save();if(!silent){render();toast('Spotify is connected, but nothing is playing right now')}return null}if(r.status===401&&await spotifyRefreshToken())return spotifyRefreshNowPlaying(silent);if(!r.ok)throw Error('spotify');const j=await r.json(),item=j.item||{};state.spotify.nowPlaying={track:item.name||'',artist:(item.artists||[]).map(a=>a.name).join(', '),album:item.album?.name||'',image:item.album?.images?.[0]?.url||'',isPlaying:!!j.is_playing,progressMs:j.progress_ms||0,durationMs:item.duration_ms||0,uri:item.uri||''};save();render();return state.spotify.nowPlaying}catch{if(!silent)toast('Spotify playback could not be refreshed');return null}}
async function spotifyPlayback(action){if(action==='refresh')return spotifyRefreshNowPlaying();if(!(await spotifyEnsureToken()))return toast('Reconnect Spotify first');const map={play:['PUT','play'],pause:['PUT','pause'],next:['POST','next'],previous:['POST','previous']},m=map[action];if(!m)return;try{const r=await fetch(`https://api.spotify.com/v1/me/player/${m[1]}`,{method:m[0],headers:{Authorization:`Bearer ${state.spotify.accessToken}`}});if(r.status===401&&await spotifyRefreshToken())return spotifyPlayback(action);if(!r.ok)throw Error('playback');if(state.spotify.nowPlaying)state.spotify.nowPlaying.isPlaying=action==='play'?true:action==='pause'?false:state.spotify.nowPlaying.isPlaying;save();setTimeout(()=>spotifyRefreshNowPlaying(true),350);render()}catch{toast('Spotify could not control the active player. Open Spotify and start playback on a device first.')}}
async function handleSpotifyCallback(){const code=new URLSearchParams(location.search).get('code');if(!code||!sessionStorage.getItem('spotify_verifier'))return;try{const body=new URLSearchParams({client_id:state.spotify.clientId,grant_type:'authorization_code',code,redirect_uri:sessionStorage.getItem('spotify_redirect'),code_verifier:sessionStorage.getItem('spotify_verifier')});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await r.json();if(!j.access_token)throw Error();state.spotify.accessToken=j.access_token;state.spotify.refreshToken=j.refresh_token||'';state.spotify.tokenExpiresAt=Date.now()+(Number(j.expires_in)||3600)*1000-60000;const p=await fetch('https://api.spotify.com/v1/me',{headers:{Authorization:`Bearer ${j.access_token}`}}).then(r=>r.json());state.spotify.connected=true;state.spotify.displayName=p.display_name||'Spotify';save();history.replaceState({},'',location.pathname+location.hash);toast('Spotify connected');render();spotifyRefreshNowPlaying(true)}catch{toast('Spotify connection could not be completed')}}
function spotifyDisconnect(){state.spotify={clientId:state.spotify.clientId,connected:false,displayName:'',accessToken:'',refreshToken:'',tokenExpiresAt:0,nowPlaying:null};save();render();toast('Spotify disconnected')}
window.__VEYRA_SPOTIFY_TEST__={spotifyAuthorizationRequest,spotifyEnsureToken,spotifyRefreshNowPlaying,spotifyPlayback};

function exportVault(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),app:'Veyra',data:state},null,2)],{type:'application/json'});download(blob,`veyra-vault-${today()}.json`)}
function exportCSV(){const cols=['date','time','meal','name','cal','p','c','f','fiber','sugar','source','confidence'];const csv=[cols.join(','),...state.meals.map(x=>cols.map(k=>`"${String(x[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');download(new Blob([csv],{type:'text/csv'}),`veyra-food-${today()}.csv`)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importVaultFile(file){const r=new FileReader();r.onload=()=>{try{const j=JSON.parse(r.result);state=deepMerge(structuredClone(DEFAULT),j.data||j);save();render();toast('Veyra Vault restored')}catch{toast('That backup could not be read')}};r.readAsText(file)}
function clearData(){if(!confirm('Delete all Veyra data stored in this browser? This cannot be undone unless you exported a Vault backup.'))return;localStorage.removeItem('veyra-state');state=structuredClone(DEFAULT);save();render();setTimeout(openOnboarding,80);toast('Local data reset')}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;save()}
function touchStreak(){if(state.lastActive!==today()){const y=iso(Date.now()-DAY);state.streak=state.lastActive===y?state.streak+1:1;state.lastActive=today()}const el=$('#streakSide');if(el)el.textContent=state.streak?`${state.streak} day${state.streak===1?'':'s'}`:'Start your streak'}
function installApp(){if(deferredInstall){deferredInstall.prompt();deferredInstall.userChoice.finally(()=>deferredInstall=null)}else openGuide(true)}
function openGuide(install=false){openModal(install?'Install Veyra':'Veyra Guide',`<div class="callout"><b>Need to change calories, protein or diet?</b><br>Tap <b>Goals</b> at the top, <b>Edit</b> beside any dashboard target, or open <b>Profile → Edit profile & goals</b>.</div><div class="guide-step"><span class="step-num">1</span><div><b>Log anything</b><small>Use +, Veyra Lens, search or voice.</small></div></div><div class="guide-step"><span class="step-num">2</span><div><b>Train live</b><small>Start a routine, check off sets, track timed work and rest.</small></div></div><div class="guide-step"><span class="step-num">3</span><div><b>Let Nexus connect it</b><small>Food, workouts, activity, sleep, pantry and history inform contextual next steps.</small></div></div><div class="guide-step"><span class="step-num">4</span><div><b>Install on iPhone</b><small>Safari → Share → Add to Home Screen → Add.</small></div></div><div class="guide-step"><span class="step-num">5</span><div><b>Install on Android</b><small>Chrome → menu → Add to Home screen / Install app.</small></div></div><div class="guide-step"><span class="step-num">6</span><div><b>Move devices</b><small>Settings → Export Veyra Vault, then import it on the new device.</small></div></div><div class="callout">Veyra is local-first. Browser permissions and AI capabilities vary by device, so every automated capture flow includes a manual confirmation/edit fallback.</div>`)}


function adultStarterTargets(){return null}
function openOnboarding(){hideWelcome();openModal('Set up your Veyra',`<div class="onboarding"><div class="onboarding-intro"><span class="eyebrow">WELCOME TO VEYRA</span><h2>Build Veyra around you.</h2><p>Start with a clean profile. Nothing is pre-filled, every target can be changed later, and you can restore a previous device at any time.</p></div><form id="onboardingForm" class="form-grid">
<label style="grid-column:1/-1">What should Veyra call you?<input name="name" required value="${esc(state.profile.name||'')}" placeholder="Your name"></label>
<label>Main goal<select name="goal"><option value="">Choose a goal</option><option value="performance">Sports / performance</option><option value="strength">Build strength</option><option value="general">General fitness</option><option value="endurance">Improve endurance</option><option value="wellness">General wellness</option><option value="maintain">Maintain routine</option><option value="custom">Something else</option></select></label>
<label style="grid-column:1/-1">Describe your goal in your own words<input name="goalText" placeholder="e.g., get stronger, improve sports performance, build a consistent routine" value="${esc(state.profile.goalText||'')}"></label>
<label>Daily activity<select name="activityLevel"><option value="">Choose...</option><option value="low">Mostly sitting / low activity</option><option value="light">Lightly active</option><option value="moderate">Moderately active</option><option value="high">Very active / sports most days</option></select></label>
<label>Training days / week<select name="trainingDays"><option value="">Choose...</option>${[1,2,3,4,5,6,7].map(n=>`<option value="${n}">${n} day${n>1?'s':''}</option>`).join('')}</select></label>
<label>Comfortable session length<select name="sessionMinutes"><option value="">Choose...</option>${[20,30,45,60,75,90].map(n=>`<option value="${n}">${n} minutes</option>`).join('')}</select></label>
<label>Training experience<select name="experienceLevel"><option value="">Choose...</option><option>beginner</option><option>intermediate</option><option>advanced</option></select></label>
<label>Diet<select name="diet"><option value="">Choose...</option><option>vegetarian</option><option>vegan</option><option>pescatarian</option><option>omnivore</option><option>custom</option></select></label>
<label>Units<select name="units"><option value="imperial">lb / in / oz</option><option value="metric">kg / cm / mL</option></select></label>
<div style="grid-column:1/-1"><label>Dietary restrictions / allergies<input name="dietaryRestrictions" placeholder="e.g., dairy-free, gluten-free, nut-free"></label></div>
<div style="grid-column:1/-1"><label>Foods you avoid or dislike<input name="foodsAvoid" placeholder="Optional"></label></div>
<div class="cuisine-picker" style="grid-column:1/-1"><h3>Favorite cuisines</h3><p class="muted">Pick any that sound good. Veyra uses these to rank recipes, but you can ask for any cuisine later.</p><div class="choice-grid">${['Indian','Italian','Mexican','Mediterranean','Chinese','Japanese','Thai','Korean','Middle Eastern','American','Greek','Vietnamese','Caribbean','French'].map(c=>`<label class="choice-chip"><input type="checkbox" name="cuisines" value="${c}"><span>${cuisineEmoji(c)} ${c}</span></label>`).join('')}</div></div>
<div class="goal-fields" style="grid-column:1/-1"><div class="card-head"><div><h3>Your daily targets</h3><small id="targetHelp">Set the targets you want Veyra to track, or leave any field blank and add it later.</small></div></div><div class="form-grid"><label>Calories<input name="calorieGoal" type="number" min="0" value="${state.profile.calorieGoal??''}" placeholder="Not set"></label><label>Protein (g)<input name="proteinGoal" type="number" min="0" value="${state.profile.proteinGoal??''}" placeholder="Not set"></label><label>Carbs (g)<input name="carbGoal" type="number" min="0" value="${state.profile.carbGoal??''}" placeholder="Not set"></label><label>Fat (g)<input name="fatGoal" type="number" min="0" value="${state.profile.fatGoal??''}" placeholder="Not set"></label><label>Fiber (g)<input name="fiberGoal" type="number" min="0" value="${state.profile.fiberGoal??''}" placeholder="Not set"></label><label>Water<input name="waterGoal" type="number" min="0" value="${state.profile.waterGoal??''}" placeholder="Not set"></label></div></div>
<div class="callout" style="grid-column:1/-1">Veyra and its creators provide tracking, estimates and educational guidance — not medical advice. Estimates can be wrong; users are responsible for how they use them.</div><button class="primary" style="grid-column:1/-1">Save profile & enter Veyra</button><button type="button" id="restoreFromSetup" class="secondary" style="grid-column:1/-1">I’ve used Veyra before — import JSON</button><button type="button" id="skipOnboarding" class="ghost" style="grid-column:1/-1">Skip for now — I’ll finish later</button></form></div>`);
const form=$('#onboardingForm');
form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form);for(const [k,v] of fd){if(k==='cuisines')continue;state.profile[k]=['calorieGoal','proteinGoal','carbGoal','fatGoal','fiberGoal','waterGoal','age','height','weight','trainingDays','sessionMinutes'].includes(k)?(v===''?null:+v):v}state.profile.favoriteCuisines=fd.getAll('cuisines');state.profile.dietaryRestrictions=(fd.get('dietaryRestrictions')||'').split(',').map(x=>x.trim()).filter(Boolean);state.profile.createdProfileAt=state.profile.createdProfileAt||Date.now();state.onboardingComplete=true;state.onboardingSkipped=false;state.streak=0;state.lastActive='';save();closeModal();render();toast(`Welcome${state.profile.name?' '+state.profile.name:''}`)};
$('#restoreFromSetup').onclick=()=>$('#backupInput').click();$('#skipOnboarding').onclick=()=>{state.onboardingSkipped=true;save();closeModal();render();toast('No problem — finish setup anytime from Profile or Goals')};}
function cuisineEmoji(c){return ({Indian:'🍛',Italian:'🍝',Mexican:'🌮',Mediterranean:'🫒',Chinese:'🥡',Japanese:'🍱',Thai:'🍜',Korean:'🥢','Middle Eastern':'🧆',American:'🥪',Greek:'🥙',Vietnamese:'🍲',Caribbean:'🥭',French:'🥖'})[c]||'🍽️'}
function hideWelcome(){const w=$('#welcomeOverlay');if(w)w.hidden=true;document.body.classList.remove('welcome-open')}
function showWelcome(){const w=$('#welcomeOverlay');if(!w||state.onboardingComplete||state.onboardingSkipped)return;w.hidden=false;document.body.classList.add('welcome-open')}

function commandModal(){openModal('Veyra Command',`<form id="commandForm" class="inline-form"><input name="q" autofocus placeholder="Ask or log anything…"><button class="primary">Go</button></form><div class="command-results">${['I ate MorningStar crumbles','Start Push Day','I ran for 30 minutes','What should I eat next?','Show my progress','Import activity screenshot'].map(x=>`<button class="command-result cmd-suggest">${x}</button>`).join('')}</div>`);const run=q=>{closeModal();if(q.toLowerCase().includes('import'))lens('activity');else handleCommand(q)};$('#commandForm').onsubmit=e=>{e.preventDefault();run(new FormData(e.currentTarget).get('q'))};$$('.cmd-suggest').forEach(b=>b.onclick=()=>run(b.textContent))}

$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#commandBtn').onclick=commandModal;$('#voiceQuick').onclick=startVoice;$('#guideBtn').onclick=()=>openGuide();$('#themeBtn').onclick=toggleTheme;$('#fab').onclick=quickAddModal;$('#imageInput').onchange=e=>{const f=e.target.files[0];if(f)processImage(f);e.target.value=''};$('#backupInput').onchange=e=>{const f=e.target.files[0];if(f)importVaultFile(f);e.target.value=''};
window.addEventListener('hashchange',()=>{route=(location.hash||'#today').slice(1);render()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false});$('#installBtn').onclick=installApp;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();commandModal()}if(e.key==='Escape')closeModal()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
document.documentElement.dataset.theme=state.theme;{const cid=configuredSpotifyClientId();if(cid)state.spotify.clientId=cid;}save();render();handleSpotifyCallback();$('#welcomeNew').onclick=openOnboarding;$('#welcomeRestore').onclick=()=>$('#backupInput').click();$('#welcomeSkip').onclick=()=>{state.onboardingSkipped=true;hideWelcome();save();render();toast('Explore freely — setup is always in Profile or Goals')};setTimeout(()=>{const el=$('#streakSide');if(el)el.textContent=state.streak?`${state.streak} day${state.streak===1?'':'s'}`:'0 days • start fresh';showWelcome()},120);
