/* Veyra Intelligence Gateway — Cloudflare Worker.
   Lookup-only: receives food/public-page queries, never a user's Veyra history.
   No key is required for the default deployment. If a higher-quota USDA key is
   desired, store it as the Worker secret FDC_API_KEY; never put it in GitHub. */
const CORS={'access-control-allow-origin':'*','access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'content-type','cache-control':'public, max-age=300'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...CORS,'content-type':'application/json; charset=utf-8'}});
const text=(data,status=200)=>new Response(data,{status,headers:{...CORS,'content-type':'text/plain; charset=utf-8'}});
const n=v=>Number.isFinite(+v)?+v:0, round=v=>Math.round(n(v)*10)/10;
function safePublicUrl(raw){try{const u=new URL(raw);if(!/^https?:$/.test(u.protocol))return null;const h=u.hostname.toLowerCase();if(h==='localhost'||h.endsWith('.local')||/^127\.|^10\.|^192\.168\.|^169\.254\.|^172\.(1[6-9]|2\d|3[01])\./.test(h))return null;return u}catch{return null}}
async function jfetch(url,init={}){const r=await fetch(url,init);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function offItem(p){const g=n(p.serving_quantity)||100,f=g/100,x=p.nutriments||{};return {name:p.product_name||'Food',brand:p.brands||'',servingLabel:p.serving_size||`${g} g`,servingGrams:g,cal:round(n(x['energy-kcal_100g'])*f),p:round(n(x.proteins_100g)*f),c:round(n(x.carbohydrates_100g)*f),f:round(n(x.fat_100g)*f),fiber:round(n(x.fiber_100g)*f),sugar:round(n(x.sugars_100g)*f),source:'Open Food Facts via Veyra Intelligence Gateway',sourceUrl:p.code?`https://world.openfoodfacts.org/product/${encodeURIComponent(p.code)}`:'https://world.openfoodfacts.org/',confidence:84,_kind:'public'}}
function nutrient(food,re){const x=(food.foodNutrients||[]).find(v=>re.test(String(v.nutrientName||v.nutrient?.name||'')));return n(x?.value??x?.amount)}
function kcal(food){const xs=food.foodNutrients||[],k=xs.find(x=>/^Energy$/i.test(String(x.nutrientName||x.nutrient?.name||''))&&/kcal/i.test(String(x.unitName||x.nutrient?.unitName||'')));if(k)return n(k.value??k.amount);const legacy=xs.find(x=>String(x.nutrientNumber||x.nutrient?.number||'')==='208');if(legacy)return n(legacy.value??legacy.amount);const kj=xs.find(x=>/^Energy$/i.test(String(x.nutrientName||x.nutrient?.name||''))&&/^kJ$/i.test(String(x.unitName||x.nutrient?.unitName||'')));return kj?n(kj.value??kj.amount)/4.184:0}
function usdaItem(f){const g=/^g$/i.test(f.servingSizeUnit||'')&&n(f.servingSize)>0?n(f.servingSize):100,fac=g/100;return {name:f.description||'USDA food',brand:f.brandName||f.brandOwner||'',servingLabel:f.householdServingFullText||`${round(g)} g reference`,servingGrams:g,cal:round(kcal(f)*fac),p:round(nutrient(f,/^Protein$/i)*fac),c:round(nutrient(f,/Carbohydrate/i)*fac),f:round(nutrient(f,/Total lipid|Total Fat/i)*fac),fiber:round(nutrient(f,/Fiber/i)*fac),sugar:round(nutrient(f,/Sugars/i)*fac),source:'USDA FoodData Central via Veyra Intelligence Gateway',sourceUrl:f.fdcId?`https://fdc.nal.usda.gov/food-details/${f.fdcId}/nutrients`:'https://fdc.nal.usda.gov/',confidence:/Branded/i.test(f.dataType||'')?86:80,_kind:'public'}}
async function food(q,env){const off=new URL('https://world.openfoodfacts.org/cgi/search.pl');off.search=new URLSearchParams({search_terms:q,search_simple:'1',action:'process',json:'1',page_size:'10',fields:'code,product_name,brands,serving_size,serving_quantity,nutriments'});const usda=new URL('https://api.nal.usda.gov/fdc/v1/foods/search');usda.search=new URLSearchParams({api_key:env.FDC_API_KEY||'DEMO_KEY',query:q,pageSize:'10'});const [a,b]=await Promise.allSettled([jfetch(off),jfetch(usda)]);const items=[];if(a.status==='fulfilled')items.push(...(a.value.products||[]).filter(x=>x.product_name).map(offItem));if(b.status==='fulfilled')items.push(...(b.value.foods||[]).map(usdaItem).filter(x=>x.cal>0));return json({query:q,items:items.slice(0,18),sourceCount:(a.status==='fulfilled')+(b.status==='fulfilled')})}
async function readPage(raw){const u=safePublicUrl(raw);if(!u)return text('Invalid public URL',400);const r=await fetch(u,{headers:{'user-agent':'Veyra-Public-Lookup/1.0','accept':'text/html,text/plain,application/xml;q=0.9,*/*;q=0.5'},redirect:'follow'});if(!r.ok)return text(`HTTP ${r.status}`,r.status);let body=(await r.text()).slice(0,900000);body=body.replace(/href=["']([^"']+)["']/gi,(m,h)=>{try{return `${m} ${new URL(h,u).href}`}catch{return m}});return text(body)}
export default {async fetch(request,env,ctx){if(request.method==='OPTIONS')return new Response(null,{headers:CORS});if(request.method!=='GET')return json({error:'GET only'},405);const u=new URL(request.url);try{if(u.pathname==='/'||u.pathname==='/health')return json({ok:true,service:'Veyra Intelligence Gateway',storesPersonalHistory:false});if(u.pathname==='/food'){const q=(u.searchParams.get('q')||'').trim();if(!q)return json({error:'Missing q'},400);return food(q.slice(0,200),env)}if(u.pathname==='/read'){const target=u.searchParams.get('url')||'';return readPage(target)}return json({error:'Not found'},404)}catch(e){return json({error:'Lookup unavailable',detail:String(e?.message||e)},502)}}};
